var _yt_www={};(function(m){var window=this;var pa;var na;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.l=function(a,b,c){a=a.split(".");c=c||m.ca;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]?c=c[d]:c=c[d]={}:c[d]=b};m.p=function(a,b){for(var c=a.split("."),d=b||m.ca,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.ea=function(){};m.fa=function(a){a.getInstance=function(){return a.Mk?a.Mk:a.Mk=new a}};
m.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ha=function(a){return void 0!==a};m.ia=function(a){return"array"==(0,m.ga)(a)};m.ja=function(a){var b=(0,m.ga)(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.q=function(a){return"string"==typeof a};m.ka=function(a){return"function"==(0,m.ga)(a)};m.la=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.ma=function(a){return a[na]||(a[na]=++pa)};
var qa=function(a,b,c){return a.call.apply(a.bind,arguments)};var ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.r=function(a,b,c){m.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?qa:ra;return m.r.apply(null,arguments)};
m.s=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.sa=function(a,b){for(var c in b)a[c]=b[c]};m.ta=function(a,b){(0,m.l)(a,b,void 0)};m.u=function(a,b){function c(){}c.prototype=b.prototype;a.F=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.CL=function(a,c,g){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};
m.ua=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};m.va=function(a){return(0,window.encodeURIComponent)(String(a))};m.wa=function(a){if(!xa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ya,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(za,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Aa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ba,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ca,"&#39;"));return a};m.Da=function(a,b){return-1!=a.indexOf(b)};
m.Ea=function(a,b){for(var c=0,d=(0,m.ua)(String(a)).split("."),e=(0,m.ua)(String(b)).split("."),g=Math.max(d.length,e.length),h=0;0==c&&h<g;h++){var k=d[h]||"",n=e[h]||"",t=RegExp("(\\d*)(\\D*)","g"),z=RegExp("(\\d*)(\\D*)","g");do{var E=t.exec(k)||["","",""],N=z.exec(n)||["","",""];if(0==E[0].length&&0==N[0].length)break;c=Fa(0==E[1].length?0:(0,window.parseInt)(E[1],10),0==N[1].length?0:(0,window.parseInt)(N[1],10))||Fa(0==E[2].length,0==N[2].length)||Fa(E[2],N[2])}while(0==c)}return c};
var Fa=function(a,b){return a<b?-1:a>b?1:0};m.Ga=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Ha=function(a){var b=(0,m.q)(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Ia=function(a,b,c){b=(0,m.Ja)(a,b,c);return 0>b?null:(0,m.q)(a)?a.charAt(b):a[b]};
m.Ja=function(a,b,c){for(var d=a.length,e=(0,m.q)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return g;return-1};m.Ka=function(a,b){return 0<=(0,m.La)(a,b)};m.Ma=function(a,b){var c=(0,m.La)(a,b),d;(d=0<=c)&&(0,m.Na)(a,c);return d};m.Na=function(a,b){m.Oa.splice.call(a,b,1)};m.Pa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.Qa=function(a,b,c){return 2>=arguments.length?m.Oa.slice.call(a,b):m.Oa.slice.call(a,b,c)};
m.Ra=function(a,b,c){return Math.min(Math.max(a,b),c)};m.Sa=function(a,b){this.x=(0,m.ha)(a)?a:0;this.y=(0,m.ha)(b)?b:0};m.Ta=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.Ua=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.Va=function(a){var b={},c;for(c in a)b[c]=a[c];return b};m.Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Xa.length;g++)c=Xa[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Ya=function(){return m.ca.navigator||null};var Za=function(){var a=m.ca.document;return a?a.documentMode:void 0};m.$a=function(a){return ab[a]||(ab[a]=0<=(0,m.Ea)(bb,a))};m.cb=function(a){return m.db&&eb>=a};m.fb=function(a){a=a.className;return(0,m.q)(a)&&a.match(/\S+/g)||[]};m.gb=function(a,b){var c=(0,m.fb)(a),d=(0,m.Qa)(arguments,1),e=c.length+d.length;(0,m.hb)(c,d);d=c.join(" ");a.className=d;return c.length==e};m.hb=function(a,b){for(var c=0;c<b.length;c++)(0,m.Ka)(a,b[c])||a.push(b[c])};
m.v=function(a){return(0,m.q)(a)?window.document.getElementById(a):a};m.w=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=(0,m.ib)("*",a,b)[0];return d||null};
m.ib=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,g=0,h;h=c[g];g++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(g=e=0;h=c[g];g++)a=h.className,"function"==typeof a.split&&(0,m.Ka)(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.jb=function(a,b){(0,m.Ta)(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in kb?a.setAttribute(kb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.x=function(a,b,c){return(0,m.lb)(window.document,arguments)};
m.lb=function(a,b){var c=b[0],d=b[1];if(!mb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',(0,m.wa)(d.name),'"');if(d.type){c.push(' type="',(0,m.wa)(d.type),'"');var e={};(0,m.Wa)(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&((0,m.q)(d)?c.className=d:(0,m.ia)(d)?m.gb.apply(null,[c].concat(d)):(0,m.jb)(c,d));2<b.length&&(0,m.nb)(a,c,b,2);return c};
m.nb=function(a,b,c,d){function e(c){c&&b.appendChild((0,m.q)(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!(0,m.ja)(g)||(0,m.la)(g)&&0<g.nodeType?e(g):(0,m.y)(ob(g)?(0,m.Pa)(g):g,e)}};m.pb=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};m.A=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};var qb=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
var rb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};m.sb=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var ob=function(a){if(a&&"number"==typeof a.length){if((0,m.la)(a))return"function"==typeof a.item||"string"==typeof a.item;if((0,m.ka)(a))return"function"==typeof a.item}return!1};m.tb=function(a){m.tb[" "](a);return a};m.ub=function(){};m.B=function(a,b){(0,m.vb)(a,(0,m.s)(m.wb,b))};
m.vb=function(a,b){a.be||(a.be=[]);a.be.push((0,m.r)(b,void 0))};m.wb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.xb=function(){this.b=[];this.Wc={}};m.yb=function(a){zb(m.Ab,arguments)};m.C=function(a,b){return a in m.Ab?m.Ab[a]:b};m.Bb=function(a){zb(m.Cb,arguments)};m.D=function(a,b){(0,m.ka)(a)&&(a=(0,m.Db)(a));return window.setTimeout(a,b)};m.Eb=function(a,b){(0,m.ka)(a)&&(a=(0,m.Db)(a));return window.setInterval(a,b)};m.F=function(a){window.clearTimeout(a)};m.Fb=function(a){window.clearInterval(a)};
m.Db=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw(0,m.Gb)(b),b;}}:a};m.Gb=function(a,b){if(window&&window.yterr){var c=(0,m.p)("yt.www.errors.log");if(c)c(a,b);else{var c=(0,m.C)("ERRORS")||[],d=(0,m.C)("ERRORS_WITH_LEVEL")||[];c.push(a);d.push([a,b]);(0,m.yb)("ERRORS",c);(0,m.yb)("ERRORS_WITH_LEVEL",d)}}};m.Hb=function(a){zb(m.Ib,arguments)};m.Jb=function(a){return a in m.Ib};
m.Kb=function(a,b,c){var d=b||{};if(a=a in m.Ib?m.Ib[a]:c)for(var e in d)a=a.replace(RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var zb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.G=function(a,b,c){var d=Mb();if(d){var e=d.subscribe(a,function(){if(!m.Nb||m.Nb!=e){var d=arguments,h=function(){Ob[e]&&b.apply(c||window,d)};try{Pb[a]?h():(0,m.D)(h,0)}catch(k){(0,m.Gb)(k)}}},c);Ob[e]=!0;Qb[a]||(Qb[a]=[]);Qb[a].push(e);return e}return 0};
m.Rb=function(a){var b=Mb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.y)(a,function(a){b.unsubscribeByKey(a);delete Ob[a]}))};m.H=function(a,b){var c=Mb();return c?c.publish.apply(c,arguments):!1};var Sb=function(a,b){Pb[a]=!0;var c=Mb();c&&c.publish.apply(c,arguments);Pb[a]=!1};var Mb=function(){return(0,m.p)("yt.pubsub.instance_")};
m.Tb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.j=(0,m.Db)(d||null);this.i=(0,m.Db)(e||null);this.g=[]};m.Ub=function(a){a.name in Vb&&Wb(a.name);Vb[a.name]={reqs:[],disable:(0,m.r)(a.disable,a)};(0,m.y)(a.deps,function(b){if(!(b in Vb))throw Error("Module "+b+" required by "+a.name);Vb[b].reqs.push(a.name)});a.enable()};var Wb=function(a){if(a in Vb){var b=Vb[a];(0,m.y)(b.reqs,function(a){Wb(a)});try{b.disable()}catch(c){}delete Vb[a]}};
m.Xb=function(a){return a&&"readyState"in a?a.readyState:0};var Yb=function(){if((0,m.C)("SCHEDULE_AJAX")&&window.XMLHttpRequest&&!Zb){$b=(0,m.C)("SCHEDULER_BUFFER_LENGTH");var a=window.XMLHttpRequest;ac=a.prototype.abort;bc=a.prototype.open;Zb=a.prototype.send;a.prototype.abort=cc;a.prototype.open=dc;a.prototype.send=ec}};var cc=function(){fc(!0);ac.call(this)};var dc=function(){this.url=arguments[1];bc.apply(this,arguments)};
var ec=function(){var a=this,b=arguments;if(a.url&&a.url.match(gc))Zb.apply(a,b);else{if("onloadend"in a)a.addEventListener("loadend",function(){4==(0,m.Xb)(a)&&fc(!0)},!1);else{var c=a.onreadystatechange;a.onreadystatechange=function(){4==(0,m.Xb)(a)&&fc(!0);c&&c.apply(this,arguments)}}hc.push(function(){Zb.apply(a,b)});fc()}};
var fc=function(a){a&&(ic=!1,(0,m.F)(jc));if(!ic&&hc.length)if($b&&!kc())(0,m.F)(lc),lc=(0,m.D)(fc,100);else{ic=!0;a=hc.shift();try{a()}catch(b){fc(!0)}jc=(0,m.D)((0,m.s)(fc,!0),5E3)}};
var kc=function(){var a=$b,b=(0,m.p)("yt.player.getPlayerByElement");if(!b)return!0;var b=b("player-api"),c=(0,m.C)("ADS_DATA");return b&&(!c||!c.show_instream)&&b.getVideoLoadedFraction&&b.getDuration&&b.getCurrentTime&&b.getPlayerState?(c=b.getVideoLoadedFraction()*b.getDuration()-b.getCurrentTime(),0>=b.getPlayerState()||c>a||0.3<b.getVideoLoadedFraction()):!0};m.I=function(a,b){return a.dataset?a.dataset[(0,m.mc)(b)]:a.getAttribute("data-"+b)};
m.nc=function(a,b){return a.dataset?(0,m.mc)(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b)};m.mc=function(a){return oc[a]||(oc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.pc=function(a,b){var c=(0,m.qc)(a);window.spf.beta?window.spf.script.load(a,c,b):window.spf.scripts.load(a,b,c)};m.rc=function(a,b){var c=(0,m.qc)(a);window.spf.beta?window.spf.script.ignore(c,b):window.spf.scripts.ignore(a,b)};
m.sc=function(a){a&&((0,m.q)(a)?(0,m.pc)(a):(0,m.ia)(a)?(0,m.y)(a,function(a){(0,m.sc)(a)}):(0,m.Ta)(a,function(a,c){(0,m.pc)(c,function(){(0,m.sc)(a)})}))};
m.qc=function(a){var b;if(a)if(-1<a.indexOf("_mod"))b=(b=a.match(tc))?b[1]:"";else{b="";var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(uc,""),b=b.replace(vc,""),b=b.replace("debug-",""),b=b.replace("tracing-",""));-1<b.indexOf("/")&&!window.spf.beta&&(b=b.split("/").join("_")+"_mod")}else b="";return b};
m.wc=function(a,b,c){a&&(c?a&&(a=(0,m.x)("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),(0,m.sb)(a).body.appendChild(a)):xc(a,b))};var xc=function(a,b){var c=new window.Image,d=""+yc++;zc[d]=c;c.onload=c.onerror=function(){b&&zc[d]&&b();delete zc[d]};c.src=a;c=eval("null")};m.Ac=function(a,b,c){Bc(c)[a]=b||(0,m.J)();b||Cc(a)};m.Dc=function(a){var b=Bc(void 0);return a in b};
var Ec=function(a,b,c){var d=Fc(c).span;c=Bc(c);"number"==typeof b?d[a]=b:b in c&&(d[a]=(0,m.J)()-c[b])};
m.Gc=function(a){var b=(0,m.C)("TIMING_ACTION"),c=!!(0,m.C)("TIMING_WFF"),d=Bc(a);if(b&&d._start&&(c&&d.vr||!c&&(d.ol||d.aft))){var d=Bc(a),b=Fc(a).span,e=(0,m.Hc)(a);if(c=(0,m.p)("yt.timing.reportbuilder_")){if(c=c.apply(null,[d,b,e,a]))Ic(c),(0,m.Jc)(a);a=window.NaN}else{var c={v:2,s:"youtube",action:(0,m.C)("TIMING_ACTION")},g=(0,m.C)("TIMING_INFO")||{},h;for(h in g)e[h]=g[h];h=e.srt;delete e.srt;var k;h||0===h||(k=m.Kc.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&
e.pt&&(h=e.pt));if(h||0===h)e.srt=h;d.aft||(d.aft=d.pbr&&d.pbs>d.pbr?d.pbr:d.pbs?d.pbs:d.vr&&d.cl&&d.cl>d.vr?d.cl:d.vr?d.vr:d.ol);d.vr&&d.gv&&(b.vl=Math.round(d.vr-d.gv));g=d._start;if(!Lc){k||(k=m.Kc.timing||{});var n;i:if(n=k,n.msFirstPaint)n=Math.max(0,n.msFirstPaint);else{var t=window.chrome;if(t&&(t=t.loadTimes,(0,m.ka)(t))){var t=t(),z=1E3*Math.min(t.requestTime||window.Infinity,t.startLoadTime||window.Infinity),z=window.Infinity===z?0:n.navigationStart-z;n=Math.max(0,Math.round(1E3*t.firstPaintTime+
z)||0);break i}n=0}0<n&&n>g&&(d.fpt=n);n=k.redirectEnd-k.redirectStart;0<n&&(b.rtime_=n);n=k.domainLookupEnd-k.domainLookupStart;0<n&&(b.dns_=n);n=k.connectEnd-k.connectStart;0<n&&(b.tcp_=n);n=k.connectEnd-k.secureConnectionStart;k.secureConnectionStart&&0<n&&(b.stcp_=n);n=k.responseStart-k.requestStart;0<n&&(b.req_=n);n=k.responseEnd-k.responseStart;0<n&&(b.rcv_=n);Lc=!0}for(var E in e)"_"!=E.charAt(0)&&(c[E]=e[E]);E={};k=[];for(var N in d)"_"!=N.charAt(0)&&(n=Math.max(Math.round(d[N]-g),0),E[N]=
n,k.push(N+"."+n));c.rt=k.join(",");N={};var d=[],W;for(W in b)"_"!=W.charAt(0)&&(N[W]=b[W],d.push(W+"."+b[W]));c.it=d.join(",");Ic(c);(W=(0,m.p)("ytdebug.logTiming"))&&W(c,E,N);(0,m.Jc)(a);a=E.aft+(h||0)}}else a=window.NaN;return a};
m.Mc=function(a,b,c){c={v:2,s:"youtube",action:c?"watch7ad_html5":"watch7ad"};var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var g in b)"_"!=g.charAt(0)&&(c[g]=b[g]);a=(0,m.C)("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Ic(c)};var Ic=function(a){var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];(0,m.wc)(b+"?"+c.substring(1))};var Bc=function(a){return Fc(a).tick};
m.Hc=function(a){return Fc(a).info};var Fc=function(a){return(0,m.p)("ytcsi."+(a||"")+"data_")||(0,m.Jc)(a)};m.Jc=function(a){var b={tick:{},span:{},info:{}};(0,m.l)("ytcsi."+(a||"")+"data_",b,void 0);return b};m.Nc=function(a){if(a.classList)return a.classList;a=a.className;return(0,m.q)(a)&&a.match(/\S+/g)||[]};m.K=function(a,b){return a.classList?a.classList.contains(b):(0,m.Ka)((0,m.Nc)(a),b)};
m.L=function(a,b){a.classList?a.classList.add(b):(0,m.K)(a,b)||(a.className+=0<a.className.length?" "+b:b)};m.M=function(a,b){a.classList?a.classList.remove(b):(0,m.K)(a,b)&&(a.className=(0,m.Oc)((0,m.Nc)(a),function(a){return a!=b}).join(" "))};m.O=function(a,b,c){c?(0,m.L)(a,b):(0,m.M)(a,b)};
m.Pc=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||(0,m.Va)(Qc);this.assets=a.assets||{};this.attrs=a.attrs||(0,m.Va)(Rc);this.params=a.params||(0,m.Va)(Sc);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded};m.Tc=function(a){a instanceof m.Pc||(a=new m.Pc(a));return a};
m.Uc=function(a,b,c,d,e,g,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);g&&(k+="?"+g);h&&(k+="#"+h);return k};m.Vc=function(a){if(Wc){Wc=!1;var b=m.ca.location;if(b){var c=b.href;if(c&&(c=(0,m.Xc)(c))&&c!=b.hostname)throw Wc=!0,Error();}}return a.match(Yc)};m.Xc=function(a){return(a=(0,m.Vc)(a)[3]||null)&&(0,window.decodeURIComponent)(a)};m.Zc=function(a){a=(0,m.Vc)(a);return(0,m.Uc)(null,null,null,null,a[5],a[6],a[7])};
m.$c=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};m.ad=function(a,b,c){if((0,m.ia)(b))for(var d=0;d<b.length;d++)(0,m.ad)(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",(0,m.va)(b))};var bd=function(a,b){for(var c in b)(0,m.ad)(c,b[c],a);return a};m.cd=function(a,b){return(0,m.$c)(bd([a],b))};m.dd=function(a){this.b=a};
m.ed=function(a){a=(a.b.cookie||"").split(m.fd);for(var b=[],c=[],d,e,g=0;e=a[g];g++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,Gv:c}};m.gd=function(a,b,c){m.hd.set(""+a,b,c,"/","youtube.com")};m.id=function(a,b){return m.hd.get(""+a,b)};m.jd=function(a){a=bd([],a);a[0]="";return a.join("")};
var kd=function(a){a=(0,m.ld)(a);a=null===a?null:a.split(".").reverse();return(null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
m.md=function(a,b){var c=(0,m.Xc)(a);if(c==(0,m.Xc)(window.location.href)||!c&&0==a.lastIndexOf("/",0)){var c=(0,m.Zc)(a),d=c.indexOf("#");if(c=0>d?c:c.substr(0,d)){for(var e=d=0;e<c.length;++e)d=31*d+c.charCodeAt(e),d%=4294967296;c="s_tempdata-"+d;d=b?(0,m.jd)(b):"";(0,m.gd)(c,d,5)}}};m.nd=function(a,b,c){c=c||"";window.location=(0,m.cd)(a,b||{})+c};m.od=function(a){(window.ytspf||{}).enabled?window.spf.navigate(a):(0,m.nd)(a)};
var pd=function(a,b,c){var d=(0,m.C)("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&(0,m.md)(a,b);if(c)return!1;(0,m.od)(a);return!0};
m.qd=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||m.ca;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//www.google.com/tools/feedback",g=d.GOOGLE_FEEDBACK_START;if(g)g.apply(d,arguments);else{var e=e+"/load.js?",h;for(h in a)g=a[h],null!=g&&!(0,m.la)(g)&&(e+=(0,window.encodeURIComponent)(h)+"="+(0,window.encodeURIComponent)(g)+"&");h=d.document;d=h.createElement("script");d.src=e;h.body.appendChild(d)}};
m.rd=function(){var a=window.GOOGLE_FEEDBACK_DESTROY_FUNCTION;a&&a()};var sd=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var td=function(a){return(a=a.exec(m.ud))?a[1]:""};m.vd=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.y)(a.childNodes,function(a){b.appendChild((0,m.vd)(a))}):b.innerHTML=a.innerHTML;return b};
var wd=function(){this.i=this.g=this.b=0;this.j="";var a=(0,m.p)("window.navigator.plugins"),b=(0,m.p)("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,g=c.length;e<g;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==
a.charAt(0)||"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.j=b;b=a;this.b=b[0];this.g=b[1];this.i=b[2];if(0>=this.b){var h,k,n,t;if(m.xd)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(z){h=null}else n=window.document.body,t=window.document.createElement("object"),t.setAttribute("type","application/x-shockwave-flash"),h=n.appendChild(t);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(E){k=""}n&&t&&n.removeChild(t);(h=k||
"")?(h=h.split(" ")[1].split(","),h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.b=h[0];this.g=h[1];this.i=h[2]}};var yd=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.b>b[0]||a.b==b[0]&&a.g>b[1]||a.b==b[0]&&a.g==b[1]&&a.i>=b[2]};
var zd=function(a){return-1<a.j.indexOf("Gnash")&&-1==a.j.indexOf("AVM2")||9==a.b&&1==a.g||9==a.b&&0==a.g&&1==a.i?!1:9<=a.b};var Ad=function(a){return m.Bd?!yd(a,11,2):m.Cd?!yd(a,11,3):!zd(a)};m.Dd=function(){return m.Ed?"Webkit":m.Fd?"Moz":m.db?"ms":m.Gd?"O":null};m.Hd=function(){return m.Ed?"-webkit":m.Fd?"-moz":m.db?"-ms":m.Gd?"-o":null};m.Id=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.Jd=function(a,b){return a&&b?b instanceof m.Id?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.Kd=function(a,b){var c=(0,m.Ga)(b);if(void 0===a.style[c]){var d=(0,m.Dd)()+(0,m.Ha)(b);if(void 0!==a.style[d])return d}return c};m.Ld=function(a,b){var c=(0,m.sb)(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""};
m.Md=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.Nd=function(a,b){a.style.height=(0,m.Md)(b,!0)};m.Od=function(a,b){a.style.width=(0,m.Md)(b,!0)};m.Pd=function(a,b){a.style.display=b?"":"none"};m.Qd=function(a){var b=m.Rd,c=(0,m.C)("FEEDBACK_LOCALE_EXTRAS",{});a?(0,m.Wa)(b,a):(0,m.Wa)(b,c);return b};
m.Sd=function(a){var b=(0,m.C)("SESSION_INDEX"),c=(0,m.C)("FEEDBACK_BUCKET_ID");a={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005",locale:(0,m.C)("FEEDBACK_LOCALE_LANGUAGE"),productId:(a||"59")+""};b&&(a.authuser=b+"");c&&(a.bucket=c);return a};
m.Td=function(a,b){try{var c=(0,m.Qd)(b);try{var d,e=(0,m.p)("yt.player.getPlayerByElement");(d=e?e("player-api"):null)&&d.pauseVideo&&d.pauseVideo();var g=wd.getInstance();c.flashVersion=g.getVersion().join(".");d&&(c.playback_id=d.getVideoData().cpn)}catch(h){}var k=(0,m.Sd)(a);(0,m.rd)();(0,m.qd)(k,c);return!1}catch(n){return!0}};m.Ud=function(){var a=(0,m.id)("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Vd[d]=c.toString())}};
var Wd=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var Xd=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Yd=function(a){a=void 0!==m.Vd[a]?m.Vd[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Zd=function(a,b){return!!(((0,m.Yd)("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var $d=function(a,b,c){if((a=(0,m.v)(a))&&b&&c){c=(0,m.Tc)(c);var d=(0,m.Va)(c.attrs);d.tabindex=0;var e=(0,m.Va)(c.params);e.flashvars=(0,m.jd)(c.args);if(m.xd){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var g in d)b.setAttribute(g,d[g]);for(g in e)d=window.document.createElement("param"),d.setAttribute("name",g),d.setAttribute("value",e[g]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(g in d)b.setAttribute(g,d[g]);for(g in e)b.setAttribute(g,e[g])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.ae=function(a,b){a=(0,m.v)(a);b=(0,m.Tc)(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=be();yd(c,b.minVersion)?(c=ce(b,c),$d(a,c,b)):de(a,b,c)};
var ee=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=(0,m.Tc)(a);var d=!!b,e=(0,m.v)(a.attrs.id),g=e?e.parentNode:null;if(e&&g){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);kd(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=be();if(yd(h,a.minVersion)){var k=ce(a,h),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=k||d)&&$d(g,k,a);Ad(h)&&fe()}else de(g,a,h);c&&c()}else(0,m.D)(function(){ee(a,
b,c)},50)}};var de=function(a,b,c){0==c.b&&b.fallback?b.fallback():0==c.b&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+(0,m.Kb)("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var ce=function(a,b){return zd(b)&&a.url||(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!yd(b,9,1,58)?!1:!0)&&a.urlV9As2||a.urlV8||a.url};
var be=function(){var a=wd.getInstance(),b=m.Ud.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var fe=function(){var a=(0,m.v)("flash10-promo-div"),b=(0,m.Zd)(m.Ud.getInstance(),107);a&&!b&&m.P.show(a)};m.ge=function(a){var b;b=(b=a.match(he))?b[1]:"";window.spf.beta?window.spf.style.load(a,b):window.spf.styles.load(a,void 0,b)};
m.ie=function(){var a=(0,m.p)("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),(0,m.l)("yt.player.utils.videoElement_",a,void 0));return a};m.je=function(){if(2.2==m.ke)return!0;var a=(0,m.ie)();try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};m.le=function(){};
var me=function(a){if(a instanceof m.le)return a;if("function"==typeof a.Bc)return a.Bc(!1);if((0,m.ja)(a)){var b=0,c=new m.le;c.next=function(){for(;;){if(b>=a.length)throw m.ne;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};m.oe=function(a,b,c){if((0,m.ja)(a))try{(0,m.y)(a,b,c)}catch(d){if(d!==m.ne)throw d;}else{a=me(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.ne)throw e;}}};
var pe=function(a){if((0,m.ja)(a))return(0,m.Pa)(a);a=me(a);var b=[];(0,m.oe)(a,function(a){b.push(a)});return b};var qe=function(){};m.re=function(){};m.se=function(a){this.b=a};m.te=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.b=a};var ue=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.b=a};
m.ve=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.we=function(a){return(0,m.xe)(new m.ye(void 0),a)};m.ye=function(a){this.b=a};m.xe=function(a,b){var c=[];ze(a,b,c);return c.join("")};
var ze=function(a,b,c){switch(typeof b){case "string":Ae(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if((0,m.ia)(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],ze(a,a.b?a.b.call(b,String(g),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=
typeof e&&(c.push(d),Ae(g,c),c.push(":"),ze(a,a.b?a.b.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var Ae=function(a,b){b.push('"',a.replace(Be,function(a){if(a in Ce)return Ce[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Ce[a]=e+b.toString(16)}),'"')};m.De=function(a){this.b=a};var Ee=function(a){this.b=a};var Fe=function(a){this.data=a};
var Ge=function(a){return!(0,m.ha)(a)||a instanceof Fe?a:new Fe(a)};m.He=function(a){a=a.data;if(!(0,m.ha)(a))throw"Storage: Invalid value was encountered";return a};var Ie=function(a){this.b=a};m.Je=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.J)()||!!b&&b>(0,m.J)()};m.Ke=function(a){this.b=a};m.Le=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.J)()+1E3*d:0;if((d=d?m.Me:m.Ne)&&window.JSON){(0,m.q)(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};
m.Oe=function(a){if(!m.Ne&&!m.Me||!window.JSON)return null;var b;try{b=m.Ne.get(a)}catch(c){}if(!(0,m.q)(b))try{b=m.Me.get(a)}catch(d){}if(!(0,m.q)(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};m.Pe=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?(0,m.Qe)().volume:(0,m.Ra)(a.volume,0,100);b.nonNormalized=a.nonNormalized;b.muted=void 0==a.muted?(0,m.Qe)().muted:a.muted;(0,m.Le)("yt-player-volume",b,2592E3)};
m.Qe=function(){var a={volume:100,muted:!1,nonNormalized:100},b=(0,m.Oe)("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:(0,m.Ra)(b.volume,0,100);a.nonNormalized=(0,window.isNaN)(b.nonNormalized)?a.volume:b.nonNormalized;a.muted=void 0==b.muted?!1:b.muted;return a};
var Re=function(a,b){this.j=this.If=a;this.D=b;this.A=!1;this.b={};this.N=this.C=null;this.L=new m.xb;(0,m.B)(this,this.L);this.i={};this.k=this.R=this.g=this.$=this.oa=null;this.V=!1;this.S=this.K=null;this.Q={};this.ha=["onReady"];this.da=0;if(this.B=!!(0,m.C)("PLAYER_ENABLE_SHARED_UI"))this.If=window.document.createElement("div"),this.j.appendChild(this.If),this.j.style.position="relative";this.X=!1;Se(this);this.Sj("onVolumeChange",(0,m.r)(this.Ny,this));this.Sj("onError",(0,m.r)(this.Oy,this));
this.Sj("onTabOrderChange",(0,m.r)(this.My,this))};
var Te=function(a,b){a.$=b;a.oa=b.clone();a.g=a.oa.attrs.id||a.g;"video-player"==a.g&&(a.g=a.D,a.oa.attrs.id=a.D);a.j.id==a.g&&(a.g=a.g+"-player",a.oa.attrs.id=a.g);var c;(c=a.oa.args.eurl)||(c=window.document.location.toString(),c=-1!=c.indexOf("/embed/")?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":c);a.oa.args.eurl=c;a.oa.args.enablejsapi="1";a.oa.args.playerapiid=a.D;a.R||(a.R=Ue(a,a.oa.args.jsapicallback||"onYouTubePlayerReady"));a.oa.args.jsapicallback=null;
a.B&&(a.oa.args.controls="0");(c=a.oa.attrs.width)&&(0,m.Od)(a.j,Number(c)||c);(c=a.oa.attrs.height)&&(0,m.Nd)(a.j,Number(c)||c);a.j.style.overflow="hidden"};var Ve=function(a){a.oa.loaded||(a.oa.loaded=!0,"0"!=a.oa.args.autoplay?a.b.loadVideoByPlayerVars(a.oa.args):a.b.cueVideoByPlayerVars(a.oa.args))};var We=function(a){if(!(0,m.ha)(a.oa.disable.flash)){var b=a.oa.disable,c;c=yd(be(),a.oa.minVersion);b.flash=!c}return!a.oa.disable.flash};
var Xe=function(a){var b=(0,m.v)(a.g);b&&b.stopVideo&&b.stopVideo();b&&b.logFallback&&b.logFallback();if(We(a)){var c=a.oa;b&&b.getUpdatedConfigurationData&&(b=(0,m.Tc)(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";Te(a,c);Ye(a,"flash")}};
var Ye=function(a,b){if(!a.la()){if(!b){var c;if(!(c=!a.oa.html5&&We(a))){if(!(0,m.ha)(a.oa.disable.html5)){if(c=(0,m.je)())c=Ze()||a.oa.assets.js;a.oa.disable.html5=!c;c||(a.oa.args.html5_unavailable="1")}c=!!a.oa.disable.html5}b=c?We(a)?"flash":"unsupported":"html5"}("flash"==b?a.XI:"html5"==b?a.YI:a.ZI).call(a);a.B&&!a.X&&$e(a)}};var Ze=function(){return!!(0,m.p)("yt.player.Application.create")};
var af=function(a,b){var c=a[b];return function(){try{return c.apply(a,arguments)}catch(d){d.message+=" ("+b+")",(0,m.Gb)(d,"WARNING")}}};var Se=function(a){a.A=!1;if(a.N)for(var b in a.i)a.N(b,a.i[b]);a.C=null;a.N=null;for(var c in a.b)a.b[c]=null;a.b.addEventListener=(0,m.r)(a.Sj,a);a.b.removeEventListener=(0,m.r)(a.HE,a);a.b.destroy=(0,m.r)(a.dispose,a);a.b.getPlayerType=(0,m.r)(a.GE,a);a.b.getCurrentVideoConfig=(0,m.r)(a.FE,a);a.b.loadNewVideoConfig=(0,m.r)(a.Ko,a);a.b.isReady=(0,m.r)(a.IE,a)};
var Ue=function(a,b){var c=b;if("string"==typeof b){if(a.Q[b])return a.Q[b];c=function(){var a=(0,m.p)(b);a&&a.apply(m.ca,arguments)};a.Q[b]=c}return c?c:null};var bf=function(a,b){var c="ytPlayer"+b+a.D;a.i[b]=c;m.ca[c]=function(c){(0,m.D)(function(){a.la()||a.L.J(b,c)},0)};return c};var cf=function(a){return(a=(0,m.v)(a.g))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var df=function(a){a.cancel();Se(a);a.k=null;a.oa.loaded=!1;var b=(0,m.v)(a.g);"html5"==cf(a)?a.S=b:b&&b.destroy&&b.destroy();a.B&&(0,m.A)((0,m.v)(a.g));(0,m.pb)(a.If)};var $e=function(a){a.oa.assets.js_sharedui&&(a.X=!0,(0,m.ge)(a.oa.assets.css_sharedui),(0,m.pc)(a.oa.assets.js_sharedui,(0,m.r)(function(){this.b.addEventListener("onReady",(0,m.r)(this.aH,this))},a)))};
m.ef=function(a,b){a=(0,m.v)(a);if(!a)return null;b=(0,m.Tc)(b);var c="player"+(0,m.ma)(a),d=ff[c];if(d)return d.Ko(b),d.b;d||(d=new Re(a,c),ff[c]=d,(0,m.H)("player-added",d.b),(0,m.vb)(d,(0,m.s)(gf,d)));(0,m.D)(function(){d.Ko(b)},0);return d.b};var hf=function(){for(var a in ff){var b=ff[a];b&&b.cancel()}};m.jf=function(a){if(a=(0,m.v)(a))a="player"+(0,m.ma)(a),(a=ff[a])&&a.dispose()};var gf=function(a){ff[a.getId()]=null};
m.kf=function(a){a=(0,m.v)(a);if(!a)return null;a="player"+(0,m.ma)(a);return(a=ff[a])?a.b:null};m.lf=function(){mf=!!(0,m.C)("PLAYER_WATCH_WHILE");var a=(0,m.p)("ytplayer.config"),b=(0,m.v)("player");if((0,m.C)("PLAYER_PERSISTENCE_REFACTOR")){if(a&&((0,m.ef)("player-api",a),a.loaded=!0,nf=!!b&&!(0,m.K)(b,"off-screen")),of=(0,m.Eb)(pf,5E3),a=qf())a.addEventListener("onReady",pf),a.addEventListener("onStateChange",pf)}else a&&!a.loaded&&((0,m.ef)("player-api",a),a.loaded=!0)};
m.rf=function(){(0,m.Fb)(of);var a=qf();a&&(a.removeEventListener("onReady",pf),a.removeEventListener("onStateChange",pf))};var qf=function(){var a=(0,m.p)("yt.player.getPlayerByElement");return a?a("player-api"):null};var pf=function(){sf++;var a=(0,m.K)((0,m.v)("player"),"off-screen"),b=qf(),b=1==(b&&b.isReady()?b.getPlayerState():void 0);nf?(a&&tf("active PP off-screen"),mf||"watch"==(0,m.C)("PAGE_NAME")||tf("active PP off watch")):(b&&tf("inactive PP playing"),a||tf("inactive PP !off-screen"))};
var tf=function(a){var b=[(0,m.p)("_spf_state.nav-counter"),sf];a+="("+b.join(",")+")";(0,m.Gb)(Error(a),"WARNING")};m.uf=function(){return!!(0,m.p)("yt.scheduler.instance")};m.vf=function(a,b){void 0===b&&(b=window.NaN);var c=(0,m.p)("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):(0,m.D)(a,b||0)};m.wf=function(a){for(var b=0,c=a.length;b<c;b++)(0,m.xf)(a[b])};
var yf=function(){(0,m.Ac)("ol");zf("init");var a=(0,m.C)("PAGE_NAME");a&&zf("init-"+a);(0,m.Gc)()};var zf=function(a){(0,m.uf)()?Af.push((0,m.vf)((0,m.s)(m.H,a),0)):(0,m.H)(a)};var Bf=function(){(0,m.wf)(Af);Af.length=0;var a=(0,m.C)("PAGE_NAME");a&&Sb("dispose-"+a);Sb("dispose")};var Cf=function(){yf()};var Df=function(){Bf()};
var Ef=function(a,b,c){for(var d=window.document.getElementsByTagName("script"),e=!1,g=0,h=d.length;g<h;g++)if(0<d[g].src.indexOf("/debug-")){e=!0;break}e&&(d=Error(),d.message=a,d.fileName=b,d.lineNumber=c,(0,m.Gb)(d))};var Ff=function(){Gf()};var Gf=function(){Hf=1;(0,m.Jc)(void 0);Cc("mark_navigation_requested");If(Jf);Sb("navigate")};var Kf=function(a){Lf(0,a.detail.part)};var Lf=function(a,b){var c=1==Hf;Hf=2;c?(If(Mf),Nf()):If(Of);b.swfcfg&&Pf(b.swfcfg)};var Qf=function(){};var Rf=function(){};
var Sf=function(a){Tf(0,a.detail.response)};var Tf=function(a,b){var c=1==Hf;Hf=3;(0,m.Ac)("_start",b.timing.responseStart);var d;d=b.timing;d=Math.max(0,d.responseStart-d.navigationStart);(0,m.Hc)(void 0).srt=d;Ec("req",b.timing.responseStart-b.timing.fetchStart);c&&(If(Uf),Nf());b.swfcfg&&Pf(b.swfcfg)};var Vf=function(){Wf()};var Wf=function(){If(Xf);yf();Hf=0};var Yf=function(a){(0,m.Gb)(a.detail.err)};var Zf=function(a,b){(0,m.Gb)(b)};var $f=function(){ag()};var bg=function(){};
var Nf=function(){window.scroll(0,0);Bf();for(var a in m.Ab)delete m.Ab[a];mf||((a=qf())&&a.stopVideo&&a.stopVideo(),nf=!1);(0,m.C)("PLAYER_PERSISTENCE_REFACTOR")&&pf()};var Pf=function(a){(0,m.Dc)("cfg")||(0,m.Ac)("cfg");(0,m.ta)("ytplayer.config",null);hf();if(a=a||null){var b=qf(),c=!0;mf&&b&&b.getVideoData&&(c=b.getVideoData().video_id!=a.args.video_id);c&&(0,m.ef)("player-api",a);a=(0,m.Tc)(a);nf=a.loaded=!0}(0,m.C)("PLAYER_PERSISTENCE_REFACTOR")&&pf();(0,m.ta)("ytplayer.config",a)};
var If=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.innerHTML="<dt><dd>",window.document.body.appendChild(b));(0,m.D)(function(){var c=a[0],d=a[1],e=a[2];b.className="";var g=b.style;g.transitionDuration=g.webkitTransitionDuration=c+"ms";g.width=d+"%";(0,m.F)(cg);cg=(0,m.D)(function(){b.className=e},c)},0)};
var ag=function(){var a=Xf[0]+50;(0,m.F)(cg);cg=(0,m.D)(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var dg=function(){m.Tb.call(this,"www/base");this.b=0};var eg=function(a){(a=a.detail.name)&&Wb(a)};var fg=function(a,b){var c;c=-1<b.indexOf("_mod")?(c=b.match(gg))?c[1]+"/"+c[2]:"":b;c&&Wb(c)};var hg=function(){(0,m.Ub)(new dg);var a=(0,m.p)("yt.actionQueue");if(a){var b=window.yt;(0,m.y)(a,function(a){b[a[0]].apply(b,a[1])});delete b.actionQueue}};
var ig=function(){var a=jg.readyState;a&&"complete"!==a&&"loaded"!==a||(jg.removeEventListener?jg.removeEventListener("load",ig,!1):jg.detachEvent&&jg.detachEvent("onreadystatechange",ig),window.spf?hg():(0,window.setTimeout)(ig,0))};m.ba=[];m.kg=m.kg||{};m.ca=this;na="closure_uid_"+(1E9*Math.random()>>>0);pa=0;m.J=Date.now||function(){return+new Date};
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.r.apply(null,c)}return(0,m.r)(this,a)};var ya=/&/g,za=/</g,Aa=/>/g,Ba=/"/g,Ca=/'/g,xa=/[&<>"']/;m.Oa=Array.prototype;m.La=m.Oa.indexOf?function(a,b,c){return m.Oa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if((0,m.q)(a))return(0,m.q)(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};m.y=m.Oa.forEach?function(a,b,c){m.Oa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.q)(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
m.Oc=m.Oa.filter?function(a,b,c){return m.Oa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,h=(0,m.q)(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[g++]=n)}return e};m.lg=m.Oa.map?function(a,b,c){return m.Oa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=(0,m.q)(a)?a.split(""):a,h=0;h<d;h++)h in g&&(e[h]=b.call(c,g[h],h,a));return e};
m.mg=m.Oa.reduce?function(a,b,c,d){d&&(b=(0,m.r)(b,d));return m.Oa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.y)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.ng=m.Oa.some?function(a,b,c){return m.Oa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.q)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return!0;return!1};
m.og=m.Oa.every?function(a,b,c){return m.Oa.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.q)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&!b.call(c,e[g],g,a))return!1;return!0};m.f=m.Sa.prototype;m.f.clone=function(){return new m.Sa(this.x,this.y)};m.f.ceil=(0,m.aa)(1);m.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};m.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};m.f.scale=(0,m.aa)(3);var Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");t:{var pg=m.ca.navigator;if(pg){var qg=pg.userAgent;if(qg){m.ud=qg;break t}}m.ud=""};var eb;var wg;var ab;var bb;var ug;var tg;m.Gd=(0,m.Da)(m.ud,"Opera")||(0,m.Da)(m.ud,"OPR");m.db=(0,m.Da)(m.ud,"Trident")||(0,m.Da)(m.ud,"MSIE");m.Fd=(0,m.Da)(m.ud,"Gecko")&&!(0,m.Da)(m.ud.toLowerCase(),"webkit")&&!((0,m.Da)(m.ud,"Trident")||(0,m.Da)(m.ud,"MSIE"));m.Ed=(0,m.Da)(m.ud.toLowerCase(),"webkit");m.sg=m.Ed&&(0,m.Da)(m.ud,"Mobile");tg=Ya();ug=tg&&tg.platform||"";m.Cd=(0,m.Da)(ug,"Mac");m.Bd=(0,m.Da)(ug,"Win");m.rg=(0,m.Da)(ug,"Linux");m.vg=!!Ya()&&(0,m.Da)(Ya().appVersion||"","X11");
bb=function(){var a="",b;if(m.Gd&&m.ca.opera)return a=m.ca.opera.version,(0,m.ka)(a)?a():a;m.Fd?b=/rv\:([^\);]+)(\)|;)/:m.db?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.Ed&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m.ud))?a[1]:"");return m.db&&(b=Za(),b>(0,window.parseFloat)(a))?String(b):a}();ab={};wg=m.ca.document;eb=wg&&m.db?Za()||("CSS1Compat"==wg.compatMode?(0,window.parseInt)(bb,10):5):void 0;var mb;mb=!m.db||(0,m.cb)(9);m.xg=!m.Fd&&!m.db||m.db&&(0,m.cb)(9)||m.Fd&&(0,m.$a)("1.9.1");m.yg=m.db&&!(0,m.$a)("9");m.zg=m.db||m.Gd||m.Ed;var kb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.tb[" "]=m.ea;m.ub.prototype.Ve=!1;m.ub.prototype.la=function(){return this.Ve};m.ub.prototype.dispose=function(){this.Ve||(this.Ve=!0,this.H())};m.ub.prototype.H=function(){if(this.be)for(;this.be.length;)this.be.shift()()};(0,m.u)(m.xb,m.ub);m.f=m.xb.prototype;m.f.Av=1;m.f.Gl=0;m.f.M=function(a,b,c){var d=this.Wc[a];d||(d=this.Wc[a]=[]);var e=this.Av;this.b[e]=a;this.b[e+1]=b;this.b[e+2]=c;this.Av=e+3;d.push(e);return e};m.f.na=function(a,b,c){if(a=this.Wc[a]){var d=this.b;if(a=(0,m.Ia)(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Mc(a)}return!1};
m.f.Mc=function(a){if(0!=this.Gl)return this.g||(this.g=[]),this.g.push(a),!1;var b=this.b[a];if(b){var c=this.Wc[b];c&&(0,m.Ma)(c,a);delete this.b[a];delete this.b[a+1];delete this.b[a+2]}return!!b};m.f.J=function(a,b){var c=this.Wc[a];if(c){this.Gl++;for(var d=(0,m.Qa)(arguments,1),e=0,g=c.length;e<g;e++){var h=c[e];this.b[h+1].apply(this.b[h+2],d)}this.Gl--;if(this.g&&0==this.Gl)for(;c=this.g.pop();)this.Mc(c);return 0!=e}return!1};
m.f.clear=function(a){if(a){var b=this.Wc[a];b&&((0,m.y)(b,this.Mc,this),delete this.Wc[a])}else this.b.length=0,this.Wc={}};m.f.Sa=(0,m.aa)(7);m.f.H=function(){m.xb.F.H.call(this);delete this.b;delete this.Wc;delete this.g};m.Ab=window.yt&&window.yt.config_||{};(0,m.l)("yt.config_",m.Ab,void 0);m.Cb=window.yt&&window.yt.tokens_||{};(0,m.l)("yt.tokens_",m.Cb,void 0);m.Ib=window.yt&&window.yt.msgs_||{};(0,m.l)("yt.msgs_",m.Ib,void 0);m.xd="Microsoft Internet Explorer"==window.navigator.appName;var Ag=(0,m.p)("yt.pubsub.instance_")||new m.xb;m.xb.prototype.subscribe=m.xb.prototype.M;m.xb.prototype.unsubscribeByKey=m.xb.prototype.Mc;m.xb.prototype.publish=m.xb.prototype.J;m.xb.prototype.clear=m.xb.prototype.clear;(0,m.l)("yt.pubsub.instance_",Ag,void 0);var Ob=(0,m.p)("yt.pubsub.subscribedKeys_")||{};(0,m.l)("yt.pubsub.subscribedKeys_",Ob,void 0);var Qb=(0,m.p)("yt.pubsub.topicToKeys_")||{};(0,m.l)("yt.pubsub.topicToKeys_",Qb,void 0);var Pb=(0,m.p)("yt.pubsub.isSynchronous_")||{};
(0,m.l)("yt.pubsub.isSynchronous_",Pb,void 0);m.Nb=(0,m.p)("yt.pubsub.skipSubId_")||null;(0,m.l)("yt.pubsub.skipSubId_",m.Nb,void 0);m.f=m.Tb.prototype;m.f.enable=function(){(0,m.y)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.M("init-"+a,this.init,this),this.M("dispose-"+a,this.dispose,this),(0,m.C)("PAGE_NAME")==a&&this.init())},this)};m.f.init=function(){this.j&&this.j()};m.f.dispose=function(){this.i&&this.i()};m.f.disable=function(){this.dispose();this.clear()};m.f.M=function(a,b,c){a=(0,m.G)(a,b,c);this.g.push(a);return a};m.f.clear=function(){(0,m.Rb)(this.g);this.g=[]};var Vb=(0,m.p)("yt.modules.registry_")||{};(0,m.l)("yt.modules.registry_",Vb,void 0);m.Bg=null;"undefined"!=typeof window.XMLHttpRequest?m.Bg=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(m.Bg=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var Zb,$b,ac,bc,ic,lc=0,jc=0,hc=[],gc=/.+\.googlevideo\.com|c\.youtube\.com|\/videoplayback\?|spf\=navigate/g;var oc={};var uc=/-vfl[a-zA-Z0-9_+=-]+/,vc=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/,tc=/jsbin\/(?:[a-zA-Z0-9_-]+\/)*(?:(?:debug-)|(?:tracing-))?([a-zA-Z0-9_-]+?)(?:-vfl|.js)/,gg=/^([a-z]+)_(\w+)_mod$/;var zc={},yc=0,Cg=(0,m.p)("yt.net.ping.workerUrl_")||null;(0,m.l)("yt.net.ping.workerUrl_",Cg,void 0);var Cc;var Lc;m.Kc=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};Cc=m.Kc.mark?function(a){m.Kc.mark(a)}:m.ea;var Qc={enablejsapi:1},Rc={},Sc={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};m.Pc.prototype.clone=function(){var a=new m.Pc,b;for(b in this){var c=this[b];"object"==(0,m.ga)(c)?a[b]=(0,m.Va)(c):a[b]=c}return a};var Yc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Wc=m.Ed;m.fd=/\s*;\s*/;m.f=m.dd.prototype;m.f.isEnabled=(0,m.aa)(8);m.f.set=function(a,b,c,d,e,g){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');(0,m.ha)(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";g=g?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.J)()+1E3*c)).toUTCString();this.b.cookie=a+"="+b+e+d+c+g};
m.f.get=function(a,b){for(var c=a+"=",d=(this.b.cookie||"").split(m.fd),e=0,g;g=d[e];e++){if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};m.f.remove=function(a,b,c){var d=(0,m.ha)(this.get(a));this.set(a,"",0,b,c);return d};m.f.oc=(0,m.aa)(9);m.f.Mb=(0,m.aa)(10);m.f.isEmpty=(0,m.aa)(11);m.f.Sa=(0,m.aa)(6);m.f.zh=(0,m.aa)(12);m.f.clear=function(){for(var a=(0,m.ed)(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.hd=new m.dd(window.document);m.hd.g=3950;m.ld=m.Xc;var Dg=!1,Eg="";
if(window.navigator.plugins&&window.navigator.plugins.length){var Fg=window.navigator.plugins["Shockwave Flash"];Fg&&(Dg=!0,Fg.description&&(Eg=sd(Fg.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(Dg=!0,Eg="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var Gg=window.navigator.mimeTypes["application/x-shockwave-flash"];(Dg=Gg&&Gg.enabledPlugin)&&(Eg=sd(Gg.enabledPlugin.description))}else try{var Hg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),Dg=
!0,Eg=sd(Hg.GetVariable("$version"))}catch(aaa){try{Hg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),Dg=!0,Eg="6.0.21"}catch(baa){try{Hg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),Dg=!0,Eg=sd(Hg.GetVariable("$version"))}catch(caa){}}}m.Ig=Eg;var Sg;var Jg,Kg,Lg,Mg,Ng,Og,Pg;Pg=Og=Ng=Mg=Lg=Kg=Jg=!1;var Qg=m.ud;Qg&&(-1!=Qg.indexOf("Firefox")?Jg=!0:-1!=Qg.indexOf("Camino")?Kg=!0:-1!=Qg.indexOf("iPhone")||-1!=Qg.indexOf("iPod")?Lg=!0:-1!=Qg.indexOf("iPad")?Mg=!0:-1!=Qg.indexOf("Chrome")?Og=!0:-1!=Qg.indexOf("Android")?Ng=!0:-1!=Qg.indexOf("Safari")&&(Pg=!0));m.Rg=Jg;Sg=Kg;m.Tg=Lg;m.Ug=Mg;m.Vg=Ng;m.Wg=Og;m.Xg=Pg;m.Yg=function(){if(m.Rg)return td(/Firefox\/([0-9.]+)/);if(m.db||m.Gd)return bb;if(m.Wg)return td(/Chrome\/([0-9.]+)/);if(m.Xg)return td(/Version\/([0-9.]+)/);if(m.Tg||m.Ug){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.ud))return a[1]+"."+a[2]}else{if(m.Vg)return(a=td(/Android\s+([0-9.]+)/))?a:td(/Version\/([0-9.]+)/);if(Sg)return td(/Camino\/([0-9.]+)/)}return""}();m.Zg=(0,m.p)("yt.dom.getNextId_");if(!m.Zg){m.Zg=function(){return++$g};(0,m.l)("yt.dom.getNextId_",m.Zg,void 0);var $g=0};m.ah=(0,m.p)("yt.events.listeners_")||{};(0,m.l)("yt.events.listeners_",m.ah,void 0);m.bh=(0,m.p)("yt.events.counter_")||{count:0};(0,m.l)("yt.events.counter_",m.bh,void 0);(0,m.fa)(wd);wd.prototype.getVersion=function(){return[this.b,this.g,this.i]};m.f=m.Id.prototype;m.f.clone=function(){return new m.Id(this.top,this.right,this.bottom,this.left)};m.f.contains=function(a){return(0,m.Jd)(this,a)};m.f.ceil=(0,m.aa)(0);m.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.f.scale=(0,m.aa)(2);m.ch=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if(m.db)return(0,m.$a)("10.0");var a=window.document.createElement("div"),b=(0,m.Hd)();a.innerHTML='<div style="'+(b?b+"-transition:opacity 1s linear;":"")+'transition:opacity 1s linear;">';a=a.firstChild;b=a.style[(0,m.Ga)("transition")];return""!=("undefined"!==typeof b?b:a.style[(0,m.Kd)(a,"transition")]||"")});m.P={tb:function(a,b){(a=(0,m.v)(a))&&a.style&&((0,m.Pd)(a,b),(0,m.O)(a,"hid",!b))},qb:function(a){return(a=(0,m.v)(a))?!("none"==a.style.display||(0,m.K)(a,"hid")):!1},Ox:function(a){if(a=(0,m.v)(a))m.P.qb(a)?((0,m.Pd)(a,!1),(0,m.L)(a,"hid")):((0,m.Pd)(a,!0),(0,m.M)(a,"hid"))},setVisible:function(a,b){if(a=(0,m.v)(a))a.style.visibility=b?"visible":"hidden"},Aj:function(a){a=(0,m.v)(a);if(!a)return null;var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return new m.Sa(b,
c)},show:function(a){(0,m.y)(arguments,function(a){m.P.tb(a,!0)})},hide:function(a){(0,m.y)(arguments,function(a){m.P.tb(a,!1)})},toggle:function(a){(0,m.y)(arguments,m.P.Ox)},Yu:function(){return"rtl"==window.document.body.getAttribute("dir")},uq:{},tm:function(a){if(a in m.P.uq)return m.P.uq[a];var b;if((b=window.document.body.style)&&a in b)b=a;else{var c=(0,m.Dd)();c?(c=c.toLowerCase(),c+=(0,m.Ha)(a),b=!(0,m.ha)(b)||c in b?c:null):b=null}return m.P.uq[a]=b},RG:function(a){return null!=m.P.tm(a)},
setProperty:function(a,b,c){(a=(0,m.v)(a))&&a.style&&(b=m.P.tm(b))&&(a.style[b]=c)},$K:function(a){if(!(0,m.ch)())return null;var b=m.P.tm("transitionProperty"),b=(0,m.Ld)(a,b),c=m.P.tm("transitionDuration");a=(0,m.Ld)(a,c);if(!b||!a)return null;var d={},e=b.split(",");(0,m.y)(a.split(","),function(a,b){var c=e[b].trim();if(c){var n;n=-1<a.indexOf("ms")?(0,window.parseInt)(a,10):Math.round(1E3*(0,window.parseFloat)(a));d[c]=n}});return d}};m.Rd={};(0,m.fa)(m.Ud);m.Vd=(0,m.p)("yt.prefs.UserPrefs.prefs_")||{};(0,m.l)("yt.prefs.UserPrefs.prefs_",m.Vd,void 0);m.f=m.Ud.prototype;m.f.get=function(a,b){Xd(a);Wd(a);var c=void 0!==m.Vd[a]?m.Vd[a].toString():null;return null!=c?c:b?b:""};m.f.set=function(a,b){Xd(a);Wd(a);if(null==b)throw"ExpectedNotNull";m.Vd[a]=b.toString()};m.f.remove=function(a){Xd(a);Wd(a);delete m.Vd[a]};m.f.save=function(){var a;a=[];for(var b in m.Vd)a.push(b+"="+(0,window.escape)(m.Vd[b]));a=a.join("&");(0,m.gd)("PREF",a,63072E3)};
m.f.clear=function(){m.Vd={}};var he=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var dh=m.ud,dh=dh.toLowerCase();if((0,m.Da)(dh,"android")){var eh=dh.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(eh)m.ke=Number(eh[1]);else{var fh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},gh=dh.match("("+(0,m.Ua)(fh).join("|")+")");m.ke=gh?fh[gh[0]]:0}}else m.ke=void 0;m.ne="StopIteration"in m.ca?m.ca.StopIteration:Error("StopIteration");m.le.prototype.next=function(){throw m.ne;};m.le.prototype.Bc=function(){return this};(0,m.u)(m.re,qe);m.re.prototype.Sa=(0,m.aa)(5);m.re.prototype.clear=function(){var a=pe(this.Bc(!0)),b=this;(0,m.y)(a,function(a){b.remove(a)})};(0,m.u)(m.se,m.re);m.f=m.se.prototype;m.f.isAvailable=function(){if(!this.b)return!1;try{return this.b.setItem("__sak","1"),this.b.removeItem("__sak"),!0}catch(a){return!1}};m.f.set=function(a,b){try{this.b.setItem(a,b)}catch(c){if(0==this.b.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.f.get=function(a){a=this.b.getItem(a);if(!(0,m.q)(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.f.remove=function(a){this.b.removeItem(a)};
m.f.Sa=(0,m.aa)(4);m.f.Bc=function(a){var b=0,c=this.b,d=new m.le;d.next=function(){if(b>=c.length)throw m.ne;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!(0,m.q)(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.f.clear=function(){this.b.clear()};m.f.key=function(a){return this.b.key(a)};(0,m.u)(m.te,m.se);(0,m.u)(ue,m.se);var Ce={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Be=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.De.prototype.set=function(a,b){(0,m.ha)(b)?this.b.set(a,(0,m.we)(b)):this.b.remove(a)};m.De.prototype.get=function(a){var b;try{b=this.b.get(a)}catch(c){return}if(null!==b)try{return(0,m.ve)(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.De.prototype.remove=function(a){this.b.remove(a)};(0,m.u)(Ee,m.De);Ee.prototype.set=function(a,b){Ee.F.set.call(this,a,Ge(b))};Ee.prototype.sh=function(a){a=Ee.F.get.call(this,a);if(!(0,m.ha)(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};Ee.prototype.get=function(a){return(a=this.sh(a))?(0,m.He)(a):void 0};(0,m.u)(Ie,Ee);Ie.prototype.set=function(a,b,c){if(b=Ge(b)){if(c){if(c<(0,m.J)()){Ie.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.J)()}Ie.F.set.call(this,a,b)};Ie.prototype.sh=function(a,b){var c=Ie.F.sh.call(this,a);if(c)if(!b&&(0,m.Je)(c))Ie.prototype.remove.call(this,a);else return c};(0,m.u)(m.Ke,Ie);m.Ke.prototype.g=(0,m.aa)(13);var ih;var hh;hh=new m.te;m.Me=hh.isAvailable()?new m.Ke(hh):null;ih=new ue;m.Ne=ih.isAvailable()?new m.Ke(ih):null;(0,m.u)(Re,m.ub);m.f=Re.prototype;m.f.getId=function(){return this.D};m.f.Ko=function(a,b){this.la()||(Te(this,a),Ye(this,b),this.A&&Ve(this))};m.f.FE=function(){return this.$};
m.f.YI=function(){this.V||("html5"==cf(this)?(this.k="html5",this.A||this.Wg(!0)):(df(this),this.k="html5",this.S?(this.If.appendChild(this.S),this.Wg()):(this.oa.loaded=!0,this.K=(0,m.r)(function(){var a=this.If,b=this.oa.clone();(0,m.p)("yt.player.Application.create")(a,b);this.Wg()},this),this.V=!0,Ze()?this.K():((0,m.pc)(this.oa.assets.js,this.K),(0,m.ge)(this.oa.assets.css)))))};
m.f.XI=function(){var a=this.oa.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==cf(this)?(this.k="flash",this.A||ee(a,!1,(0,m.r)(this.Wg,this))):(df(this),this.k="flash",this.oa.loaded=!0,(0,m.ae)(this.If,a),this.Wg())};
m.f.Wg=function(a){var b=(0,m.v)(this.g),c=!1;try{b&&b.getApiInterface&&b.getApiInterface()&&(c=!0)}catch(d){}if(c)if(this.V=!1,a&&b.isNotServable&&b.isNotServable())Xe(this);else{Se(this);this.A=!0;a=(0,m.v)(this.g);a.addEventListener&&(this.C=af(a,"addEventListener"));a.removeEventListener&&(this.N=af(a,"removeEventListener"));b=a.getApiInterface();b=b.concat(a.getInternalApiInterface());for(c=0;c<b.length;c++){var e=b[c];this.b[e]||(this.b[e]=af(a,e))}for(var g in this.i)this.C(g,this.i[g]);Ve(this);
this.R&&this.R(this.b);this.L.J("onReady",this.b)}else this.da=(0,m.D)((0,m.r)(this.Wg,this),50)};m.f.IE=function(){return this.A};m.f.Sj=function(a,b){if(!this.la()){var c=Ue(this,b);if(c){if(!(0,m.Ka)(this.ha,a)&&!this.i[a]){var d=bf(this,a);this.C&&this.C(a,d)}this.L.M(a,c);"onReady"==a&&this.A&&(0,m.D)((0,m.s)(c,this.b),0)}}};m.f.HE=function(a,b){if(!this.la()){var c=Ue(this,b);c&&this.L.na(a,c)}};
m.f.My=function(a){a=a?rb:qb;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.f.Ny=function(a){(0,m.Pe)(a)};m.f.Oy=function(a){5!=a&&202!=a||Xe(this)};
m.f.ZI=function(){df(this);this.k="unsupported";var a=(0,m.Kb)("PLAYER_FALLBACK",void 0,'The Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>'),b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a=(0,m.Kb)("QUICKTIME_FALLBACK",void 0,'The Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>'));
b=(0,m.v)("player-unavailable");(0,m.v)("unavailable-submessage")&&b&&((0,m.v)("unavailable-submessage").innerHTML=a,(a=(0,m.w)("icon",b))&&(0,m.nc)(a,"icon")&&(a.src=(0,m.I)(a,"icon")),(0,m.M)(b,"hid"),(0,m.L)((0,m.v)("player"),"off-screen-trigger"))};m.f.GE=function(){return this.k||cf(this)};m.f.cancel=function(){(0,m.rc)(this.oa.assets.js,this.K);(0,m.F)(this.da)};m.f.aH=function(){var a=(0,m.p)("yt.player.ui.shared.init");a&&(this.b.hideUserInterface(),a(this.j,this.oa.clone()))};
m.f.H=function(){df(this);if(this.B){var a=(0,m.p)("yt.player.ui.shared.dispose");a&&a();this.X=!1}this.Q=null;for(var b in this.i)m.ca[this.i[b]]=null;this.j=this.If=this.b=null;this.oa&&(this.$=this.oa=this.oa.fallback=null);Re.F.H.call(this)};var ff={};var jh=(0,m.p)("yt.player.exports.navigate")||pd;(0,m.l)("yt.player.exports.navigate",jh,void 0);var kh=(0,m.p)("yt.player.embed")||m.ef;(0,m.l)("yt.player.embed",kh,void 0);var lh=(0,m.p)("yt.player.destroy")||m.jf;(0,m.l)("yt.player.destroy",lh,void 0);var mh=(0,m.p)("yt.player.cancelAll")||hf;(0,m.l)("yt.player.cancelAll",mh,void 0);var nh=(0,m.p)("yt.player.getPlayerByElement")||m.kf;(0,m.l)("yt.player.getPlayerByElement",nh,void 0);var oh=(0,m.p)("yt.player.exports.feedbackStart")||m.Td;
(0,m.l)("yt.player.exports.feedbackStart",oh,void 0);var of,nf=!1,sf=0,mf=!1;m.xf=(0,m.p)("yt.scheduler.instance.cancelJob")||m.ea;var Af=[];var Hf,cg,Jf=[900,60,"waiting"],Uf=[500,99,"waiting"],Mf=[300,60,"waiting"],Of=[400,99,"waiting"],Xf=[300,101,"done"];window.yt=window.yt||{};(0,m.l)("yt.setConfig",m.yb,void 0);(0,m.l)("yt.getConfig",m.C,void 0);(0,m.l)("yt.hasMsg",m.Jb,void 0);(0,m.l)("yt.pubsub.publish",m.H,void 0);(0,m.l)("yt.pubsub.subscribe",m.G,void 0);(0,m.l)("yt.setMsg",m.Hb,void 0);(0,m.l)("yt.setGoogMsg",function(a){zb(m.Ib,arguments)},void 0);(0,m.l)("yt.setAjaxToken",m.Bb,void 0);
(0,m.l)("reportTimingMaps",function(a,b,c,d){if(a)for(var e in a)(0,m.Ac)(e,a[e],d);if(c)for(var g in c)Ec(g,c[g],d);if(b)for(var h in b)a=h,c=b[h],(0,m.Hc)(d)[a]=c;return(0,m.Gc)(d)},void 0);(0,m.l)("yt.timing.reportAdToVideo",m.Mc,void 0);(0,m.u)(dg,m.Tb);
dg.prototype.enable=function(){window.onload=Cf;window.onunload=Df;window.onerror=Ef;var a=window.ytspf||{};a.enabled?(a.config=a.config||{},window.spf.beta&&!a.config["beta-use-callbacks"]?window.addEventListener&&(window.addEventListener("spfrequested",Ff),window.addEventListener("spfpartreceived",Kf),window.addEventListener("spfpartprocessed",Qf),window.addEventListener("spfreceived",Sf),window.addEventListener("spfprocessed",Vf),window.addEventListener("spferror",Yf),window.addEventListener("spfjsbeforeunload",
eg)):(0,m.sa)(a.config,{"navigate-requested-callback":Gf,"navigate-part-received-callback":Lf,"navigate-part-processed-callback":Rf,"navigate-received-callback":Tf,"navigate-processed-callback":Wf,"navigate-error-callback":Zf,"script-loading-callback":fg}),window.spf.beta&&window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.M("init",$f),this.M("dispose",bg)):window.spf.dispose();this.M("init",this.init,this);this.M("dispose",
this.dispose,this)};
dg.prototype.init=function(){(window.ytspf||{}).enabled||window.spf.dispose();Yb();var a,b;!window.ytPageFrameLoaded&&(0,m.C)("PAGEFRAME_JS")&&(a=(0,m.C)("PAGEFRAME_JS"),b=function(){(0,m.p)("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0});var c=(0,m.C)("JS_COMMON_MODULE"),d=(0,m.C)("JS_PAGE_MODULES");if(window.ytdepmap)c=(0,m.C)("JS_DELAY_LOAD",void 0),0<c?((0,m.F)(this.b),this.b=(0,m.D)(function(){a&&(0,m.pc)(a,b);window.spf.script.require(d)},c)):(a&&(0,m.pc)(a,b),window.spf.script.require(d));
else{var e={};e[c]=d;c=(0,m.C)("JS_DELAY_LOAD",void 0);0<c?((0,m.F)(this.b),this.b=(0,m.D)(function(){a&&(0,m.pc)(a,b);(0,m.sc)(e)},c)):(a&&(0,m.pc)(a,b),(0,m.sc)(e))}(0,m.lf)()};dg.prototype.dispose=function(){(0,m.F)(this.b);var a=(0,m.p)("ytbin.www.pageframe.cancelSetup");a&&a();(0,m.rf)()};
dg.prototype.disable=function(){dg.F.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequested",Ff),window.removeEventListener("spfpartreceived",Kf),window.removeEventListener("spfpartprocessed",Qf),window.removeEventListener("spfreceived",Sf),window.removeEventListener("spfprocessed",Vf),window.removeEventListener("spferror",Yf),window.removeEventListener("spfjsbeforeunload",eg));window.onload=null;window.onunload=null;window.onerror=null};
if(window.spf)hg();else{var jg=(0,m.ib)("script","spf",void 0)[0];jg&&(jg.addEventListener?jg.addEventListener("load",ig,!1):jg.attachEvent&&jg.attachEvent("onreadystatechange",ig))};})(_yt_www);
