(function(m){var window=this;var NG=function(a){if(!a.length)return 0;var b=a[0],c=b.offsetHeight;1<a.length&&(c=a[1].offsetTop-b.offsetTop);return c};var OG=function(){var a=m.uq.getInstance(),b=PG;if(!b)return[];a=(0,m.R)((0,m.X)(a,"scroll-unit"),b);if(0>=a.length)return[];var c=b.scrollTop,d=NG(a),e=b.offsetHeight,b=Math.max(Math.floor(c/d),0),c=Math.min(Math.ceil((c+e)/d),a.length);return(0,m.Qa)((0,m.Pa)(a),b,c)};
var QG=function(a,b){var c=(0,m.v)(b);if(c){var d=(0,m.X)(a,"toggled"),c=(0,m.R)(d,c);(0,m.y)(c,function(a){(0,m.M)(a,d)})}};var RG=function(a){var b=(0,m.w)("related-video",a),b={video_id:(0,m.I)(b,"video-id"),action_dismiss_video_recommendation:1},b=(0,m.cd)("/related_ajax",b);window.spf.load(b,{method:"POST",onSuccess:function(){m.P.hide(a)}})};
var SG=function(a){var b=a.currentTarget.href,c=(0,m.vs)();if(c){var d=(0,m.Fk)(b).v;if((0,m.C)("VIDEO_ID")==d){c=Math.floor(c.getCurrentTime());a=a.currentTarget;var c={t:c},d=b.split("#",2),b=d[0],d=1<d.length?"#"+d[1]:"",e=(0,m.Ri)(d),g;for(g in c)e[g]=c[g];(0,m.Pj)(e)||(d=(0,m.Fj)("#",e));a.href=b+d}}};var TG=function(a){a.stopPropagation();a=a.currentTarget;var b=(0,m.Q)(a,"video-list-item");if(b)switch((0,m.I)(a,"action")){case "hide":RG(b)}};
var UG=function(){var a=(0,m.R)("related-video-featured");(0,m.y)(a,function(a){m.P.show(a)})};var VG=function(a,b){var c=(0,m.C)("I18N_PLURAL_RULES")||function(a){return 1==a?"one":"other"};return(c=a["case"+b]||a[c(b)])?c.replace("#",b.toString()):b+""};
var WG=function(a){var b=window.location.href;b.indexOf("#")==b.length-1&&m.Ed&&(window.location.hash="#!");var b=window.document.body,c=(0,m.Rh)(b),d=[];d.push("<!DOCTYPE html>");d.push("<html><head>",a,"</head><body>","","</body></html>");a=(0,m.JA)(c,"display: none");b.appendChild(a);b=d.join("");d=a.contentDocument||a.contentWindow.document;d.open();d.write(b);d.close();m.$C=a};
var XG=function(){var a=(0,m.R)("related-video-featured");2==a.length?(0,m.K)(a[0],"related-video-featured-booster")?m.P.show(a[1]):m.P.show(a[0]):(0,m.y)(a,function(a){m.P.show(a)})};
var YG=function(a){0==a.length?UG():(0,m.aD)("watch_related",a[0],null,function(a,c){var d=c.html_content||"",e=(0,m.v)(window.pyv_related_box_id||"watch-related");e&&(0!=e.innerHTML.indexOf(d)&&e.insertBefore((0,m.Vi)(d),e.firstChild),(d=(0,m.v)("pyv-watch-related-dest-url"))&&d.setAttribute("href",m.bD),d=m.cD,(0,m.wc)(d,void 0,(0,m.Rk)(d)))})};var ZG=function(a){var b=(0,m.cd)("/related_ajax",{video_id:(0,m.C)("VIDEO_ID"),action_more_related_videos:1});window.spf.load(b,{onSuccess:a})};
var $G=function(a){if("true"==(0,m.I)(a,"loaded"))return null;(0,m.Ti)(a,"loaded","true");return(0,m.V)("/watch_ajax",{format:"XML",ca:{action_get_video_attributions_component:1,v:(0,m.C)("VIDEO_ID")},onSuccess:function(b,c){a.innerHTML=c.html_content}})};
var aH=function(a){return(0,m.V)("/insight_ajax",{format:"XML",method:"POST",ca:{action_get_statistics_and_data:1,v:(0,m.C)("VIDEO_ID")},Z:{session_token:(0,m.Yk)("insight_ajax")},onSuccess:function(b,c){a(c.html_content,c.graph_data,!0)},onError:function(){a(null,null,!1)}})};
var bH=function(a){var b=0,c=(0,m.vs)();c&&c.pauseVideo&&(c.pauseVideo(),b=c.getCurrentTime());b=Math.floor(b);c=Math.floor(b/60);return(0,m.V)("/watch_ajax",{method:"GET",ca:{action_get_report_video_component:1,video_id:(0,m.C)("VIDEO_ID"),t_mins:c,t_secs:b-60*c},onSuccess:function(b,c){a(c.report_html,!0)},onError:function(){a(null,!1)}})};
m.cH=function(a,b){var c=a.type;if((0,m.ha)(c))switch(c.toLowerCase()){case "checkbox":case "radio":a.checked=b?"checked":null;break;case "select-one":a.selectedIndex=-1;if((0,m.q)(b))for(var d=0;c=a.options[d];d++)if(c.value==b){c.selected=!0;break}break;case "select-multiple":c=b;(0,m.q)(c)&&(c=[c]);for(var e=0;d=a.options[e];e++)if(d.selected=!1,c)for(var g,h=0;g=c[h];h++)d.value==g&&(d.selected=!0);break;default:a.value=null!=b?b:""}};
var dH=function(a){var b=(0,m.qc)(a);window.spf.beta?window.spf.script.unload(b):window.spf.scripts.unload(a)};var eH=function(a,b){return VG(a in m.Ib?m.Ib[a]:{},b)};var fH=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var g=arguments[e];if(c>=g.length)return b;d.push(g[c])}b.push(d)}};var gH=function(){this.g=new m.DB(this);this.i=!1};
var hH=function(){if((0,m.C)("WATCH_LEGAL_TEXT_ENABLE_AUTOSCROLL")){var a=window.document.getElementById("watch_companion_legal_text");a&&(iH=new gH,iH.start(a))}var b=(0,m.C)("ADS_DATA");if(b){jH(b);kH=b;lH=(0,m.vs)();null!=lH&&(lH.addEventListener("onApiChange",mH),lH.addEventListener("onReady",nH));(0,m.C)("RELATED_DELAY_LENGTH")||oH();b.use_gut&&(dH("//www.googletagservices.com/tag/js/gpt.js"),(0,m.pc)("//www.googletagservices.com/tag/js/gpt.js",function(){if("googletag"in window&&(pH=window.googletag.defineSlot(b.gut_vars.tag,
[[300,250],[300,60]],"google_companion_ad_div"))){pH.set("ad_type","flash");pH.addService(window.googletag.companionAds());window.googletag.enableServices();var a=pH.getSizes();qH=a[0];rH=a[1]}}));if(b.show_afv||b.show_afc)dH("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),(0,m.pc)("//pagead2.googlesyndication.com/pagead/show_companion_ad.js",sH),(0,m.pc)("//www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22ads%22%2C%22version%22%3A%221%22%2C%22callback%22%3A%22(function()%7B%7D)%22%2C%22packages%22%3A%5B%22content%22%5D%7D%5D%7D");
b.show_afc&&tH(b);uH();b.check_status&&vH();(0,m.H)("adJavaScriptInitialized")}};var oH=function(){var a=(0,m.C)("ADS_DATA");a&&(a.show_pyv?wH(a):UG())};var vH=function(){function a(){xH=!0;"google_ad_status"in window?(0,m.Nl)("adstat=s"):(0,m.Nl)("adstat=l")}(0,m.pc)("//static.doubleclick.net/instream/ad_status.js",a);(0,m.D)(function(){xH||"google_ad_status"in window||((0,m.rc)("//static.doubleclick.net/instream/ad_status.js",a),(0,m.Nl)("adstat=f"))},5E3)};
var uH=function(){yH&&null!=lH&&null!=lH.getOptions&&(0,m.yh)(lH.getOptions())&&(0,m.Ka)(lH.getOptions(),"ad")&&lH.getOption("ad","PAGE_JAVASCRIPT_INITIALIZED",{})};var jH=function(a){zH=[];if("afv_vars"in a)for(var b in a.afv_vars)window[b]=a.afv_vars[b],zH.push(b)};var AH=function(a,b){a||(a="");b||(b=!1);var c=(0,m.v)("watch-channel-brand-div");c&&(0,m.O)(c,"collapsible",b);if(c=(0,m.v)("google_companion_ad_div"))c.innerHTML=a};
var BH=function(a){var b=Math.round(1E4*Math.random());return['<iframe src="',a,'" name="ifr_300x250ad',b,'" id="ifr_300x250ad',b,'" width="300" height="250" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join("")};var CH=function(a){return!!a.match("/[subscribe_widget|ad_companion].*render=video_wall_companion")};
var DH=function(a,b){var c=250;"video"==a&&(c=60);var d=(0,window.decodeURIComponent)(b);AH(['<iframe name="fw_ad" id="fw_ad" ','width="300" height="'+c+'" ','marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join(""));var e=(0,m.v)("fw_ad");if(e){var e=e.contentWindow?e.contentWindow:e.contentDocument.document?e.contentDocument.document:e.contentDocument,g=window.navigator.userAgent.toLowerCase(),c=-1!=g.indexOf("msie"),g=-1!=g.indexOf("opera");e.document.open();
e.document.write(d);c||g?(0,m.D)(function(){e.document.close()},7500):e.document.close()}};var sH=function(){(0,m.H)("showCompanionAdLoaded")};var EH=function(){window.google_ad_output="html";window.google_ad_height="250";window.google_ad_format="300x250_as";window.google_container_id="google_companion_ad_div"};
var FH=function(){var a=window.document.getElementById("google_companion_ad_div");if(a&&(a=a.firstElementChild))try{a.contentWindow.postMessage((0,window.encodeURIComponent)(GH)+","+(0,window.encodeURIComponent)(HH),"*")}catch(b){}};var IH=function(){var a=window.document.getElementById("movie_player");a&&a.pauseVideo()};
var wH=function(a){WG("<script>var pyvOptions = "+a.pyv_vars.iframe_json+'; for (var key in pyvOptions) { window[key] = pyvOptions[key]; } window["google_ad_request_done"] = parent.yt.www.ads.pyv.pyvWatchAfcWithPpvCallback; \x3c/script><script src="//pagead2.googlesyndication.com/pagead/show_ads.js">\x3c/script>');a.log_pyv&&(0,m.D)(function(){"google_render_ad"in window?(0,m.Nl)("pyvls"):(0,m.Nl)("pyvlf")},5E3)};
var tH=function(a){if(!JH){if(!a){if(!kH)return;a=kH}var b=(0,m.p)("google.ads.Ad");b?(JH=!0,new b(a.afv_vars.google_ad_client,"google_companion_ad_div",a.afc_vars)):KH=(0,m.D)(function(){tH(a)},200)}};var mH=function(){uH()};var nH=function(){yH=!0;uH()};var LH=function(){var a=(0,m.C)("BG_I",null),b=(0,m.C)("BG_IU",null),c=(0,m.C)("BG_P");b?(0,m.pc)(b,function(){MH=new window.botguard.bg(c)}):a&&(eval(a),MH=new window.botguard.bg(c))};
var NH=function(){return!OH&&(OH=!0,(0,m.C)("BG_P")&&((0,m.C)("BG_I")||(0,m.C)("BG_IU")))?(LH(),!0):!1};var PH=function(){var a=(0,m.cq)();m.P.hide((0,m.w)("flag-comment-step1",a));m.P.show((0,m.w)("flag-comment-step2",a));m.P.hide((0,m.w)("flag-comment-step3",a))};
var QH=function(){var a=(0,m.cq)(),b=(0,m.w)("flag-comment-form",a),c=(0,m.w)("flag-comment-block-user-input",a),d=(0,m.w)("submit-flag-comment",a),e=(0,m.w)("flag-comment-error-msg",a);m.P.hide(e);c.disabled=!0;d.disabled=!0;(0,m.V)("/comment_servlet",{format:"XML",method:"POST",ca:{flag_comment:1},Z:(0,m.ti)((0,m.im)(b)),onSuccess:function(b,c){c&&c.html_content?(m.P.hide((0,m.w)("flag-comment-step1",a)),m.P.hide((0,m.w)("flag-comment-step2",a)),m.P.show((0,m.w)("flag-comment-step3",a)),(0,m.w)("flag-comment-captcha-placeholder",
a).innerHTML=c.html_content):m.Yp.getInstance().hide()},onError:function(a,b){var k=b&&b.error_message;if(k){var n=(0,m.w)("yt-alert-message",e);(0,m.al)(n,k)}m.P.show(e);c.disabled=!1;d.disabled=!1}})};var RH=function(a){var b=(0,m.cq)(),c=(0,m.w)("abuse-type-placeholder",b);a=(0,m.Dh)(a.currentTarget,"LABEL");(0,m.al)(c,(0,m.Zk)(a));(0,m.w)("continue-flag-comment",b).disabled=!1};
var SH=function(a){var b;switch(a){case "PENDING":b=(0,m.Kb)("COMMENT_PENDING");break;case "BLOCKED":b=(0,m.Kb)("COMMENT_BLOCKED");break;case "EMAIL":b=(0,m.Kb)("COMMENT_ERROR_EMAIL");break;case "INLINE_CAPTCHAFAIL":b=(0,m.Kb)("COMMENT_CAPTCHAFAIL");break;case "SHOW_COUNTDOWN":b=(0,m.Kb)("SHOW_COUNTDOWN");break;case "FAILED_MAINTENANCE":b=(0,m.Kb)("COMMENT_FAILED_MAINTENANCE");break;case "FAILED_OWNER_LINKING":b=(0,m.Kb)("COMMENT_OWNER_LINKING");break;case "FAILED_HASLINK":b=(0,m.Kb)("FAILED_HASLINK");
break;case "FAILED_HASTAGS":b=(0,m.Kb)("FAILED_HASTAGS");break;case "FAILED_ASCIIART":b=(0,m.Kb)("FAILED_ASCIIART");break;case "FAILED_TOOSHORT":b=(0,m.Kb)("FAILED_TOOSHORT");break;case "FAILED_TOOLONG":b=(0,m.Kb)("FAILED_TOOLONG");break;case "FAILED_BADPARENT":b=(0,m.Kb)("FAILED_BADPARENT")}return b||null};
var TH=function(a,b,c){this.B=!!c;this.Va=a;this.Ur=(0,m.v)("all-comments");this.hf=(0,m.Dj)("button","post-button",a);this.Lc=(0,m.Dj)("textarea",null,a);this.Qf=null;this.b=(0,m.w)("comments-remaining",this.Va);this.A=(0,window.parseInt)((0,m.I)(this.b,"max-count"),10);this.Pf=(0,m.w)("comments-post-message",this.Va);this.Tr=(0,m.w)("yt-alert-content",this.Pf);this.g=(0,m.w)("comments-threshold-countdown",this.Va);this.k=[];this.j=[];this.i=null;this.oA=!!(0,m.C)("COMMENTS_IS_LIVE_EVENT");UH(this);
VH(this,this.Lc,"focus",this.ls);VH(this,this.Lc,"blur",this.GA);VH(this,this.Va,"submit",this.is);VH(this,this.Lc,"change",this.ks);VH(this,this.Lc,"keyup",this.ks);VH(this,this.Lc,"keydown",this.HA);b&&this.ls()};var VH=function(a,b,c,d){a.k.push((0,m.S)(b,c,(0,m.r)(d,a)))};var WH=function(a){a.Qf&&(a.Qf.innerHTML="")};var UH=function(a){var b=a.A-a.Lc.value.length;a.b.innerHTML=eH("CHARACTERS_REMAINING",b);b=0>b;(0,m.Oj)(a.b,"too-many",b);a.hf.disabled=b};
var XH=function(a,b){var c=(0,m.r)(function(){0==b?((0,m.Fb)(d),YH(this)):(b--,this.g.innerHTML=eH("SECONDS_REMAINING",b))},a);ZH(a);var d=(0,m.Eb)(c,1E3);c();a.j.push(d)};var ZH=function(a){m.P.hide(a.b);m.P.show(a.g);a.hf.disabled=!0};var YH=function(a){m.P.hide(a.g);m.P.hide(a.Pf);m.P.show(a.b);a.g.innerHTML="";a.hf.disabled=!1};
var $H=function(a,b,c){var d=SH(b)||(0,m.Kb)("COMMENT_ERROR");a.Tr.innerHTML=d;(0,m.ml)(a.Pf,"yt-alert-info","yt-alert-error");m.P.show(a.Pf);switch(b){case "INLINE_CAPTCHA":case "INLINE_CAPTCHAFAIL":(0,m.V)("/comment_servlet?gimme_captcha=1",{format:"XML",method:"POST",Z:{session_token:(0,m.Yk)("comment_servlet")},onSuccess:function(a,b){this.Qf||(this.Qf=window.document.createElement("div"),this.Qf.className="comment-captcha",(0,m.il)(this.Qf,this.Lc));this.Qf.innerHTML=b.html_content;this.hf.disabled=
!1},O:a});break;case "SHOW_COUNTDOWN":XH(a,(0,window.parseInt)(c.countdown_timer,10)||30);break;default:a.hf.disabled=!1,WH(a)}};var aI=function(a){this.ia=a;this.gt=(0,m.w)("yt-uix-pager-show-more");this.i=!!(0,m.C)("ENABLE_LIVE_COMMENTS");this.b=[];(a=(0,m.w)("comments-pagination",this.ia))&&(0,m.I)(a,"ajax-enabled")&&this.b.push((0,m.U)(this.ia,"click",(0,m.r)(this.j,this),"yt-uix-pager-button"))};
var bI=function(a,b){var c=(0,m.ib)("li","comment",void 0),c=(0,m.I)(c[c.length-1],"id"),d=a.xj?!1:!0;m.P.show("comments-loading");cI(a,c,function(a,c){c.html_content&&(m.P.hide("comments-loading"),this.xj=window.document.createElement("div"),this.xj.innerHTML=c.html_content,!d&&0<(0,m.ib)("li","comment",this.xj).length&&m.P.show(this.gt),b&&b())})};
var cI=function(a,b,c){(0,m.V)("/watch_ajax?action_get_comments=1",{format:"XML",ca:{v:(0,m.C)("VIDEO_ID"),p:1,commentthreshold:(0,m.C)("COMMENTS_THRESHHOLD"),commenttype:"everything",enable_live_comments:a.i?"yes":null,last_comment_id:b,page_size:(0,m.C)("COMMENTS_PAGE_SIZE"),source:(0,m.C)("COMMENT_SOURCE")},onSuccess:c,O:a})};var dI=function(a,b,c){a=(0,m.Dh)(a,"form");(0,m.nc)(a,"initialized")||((0,m.Ti)(a,"initialized","true"),eI=new TH(a,!b,c),b&&eI.focus())};
var fI=function(a){a=a.currentTarget;var b=(0,m.Dh)(a,null,"comment");switch((0,m.I)(a,"action")){case "approve":gI(b);break;case "block":(0,window.confirm)((0,m.Kb)("BLOCK_USER"))&&(hI(b,!0),(0,m.gb)(b,"blocked"));break;case "unblock":hI(b,!1);(0,m.Wi)(b,"blocked");break;case "flag-in-place":if(iI(!1)){var c=(0,m.v)("comment-flag-area");a=(0,m.I)(b,"id");var d=(0,m.I)(b,"author-id"),e=(0,m.Zk)((0,m.w)("author",b)),b=(0,m.w)("comment-text",b).innerHTML,g=(0,m.C)("VIDEO_ID");m.Yp.getInstance().show(c);
c=(0,m.cq)();(0,m.w)("flagged-comment-id",c).value=a;(0,m.w)("flagged-comment-author-id",c).value=d;(0,m.w)("flagged-comment-video-id",c).value=g;(0,m.al)((0,m.w)("flagged-comment-author-name",c),e);(0,m.w)("flagged-comment-text",c).appendChild((0,m.Vi)(b));(0,m.S)((0,m.w)("continue-flag-comment",c),"click",PH);(0,m.U)(c,"click",QH,"submit-flag-comment");(0,m.U)(c,"click",RH,"abuse-type-radio-input")}break;case "flag":jI(b,"mark_comment_as_spam");break;case "flag-profile-pic":jI(b,"flag_profile_pic");
break;case "unflag":a=(0,m.I)(b,"id");(0,m.V)("/comment_servlet",{format:"XML",method:"POST",Z:{unmark_comment_as_spam:a,entity_id:(0,m.C)("VIDEO_ID"),session_token:(0,m.Yk)("comment_servlet")}});break;case "hide":(0,m.gb)(b,"hidden");break;case "show":(0,m.Wi)(b,"hidden");break;case "remove":kI(b);break;case "reply":lI(b);break;case "realtime-reply":iI(!0)&&(eI||(a=(0,m.w)("comments-textarea",(0,m.v)("comments-view")),dI(a)),a=eI,a.reset(),a.focus());break;case "vote-up":mI(b,!0);break;case "vote-down":mI(b,
!1);break;case "show-parent":nI(b)}};var iI=function(a){return(0,m.C)("COMMENTS_SIGNIN_URL")?((0,m.nd)((0,m.C)("COMMENTS_SIGNIN_URL")),!1):a&&(0,m.C)("COMMENTS_CHANNEL_CREATE_URL")?((0,m.nd)((0,m.C)("COMMENTS_CHANNEL_CREATE_URL")),!1):(0,m.C)("COMMENTS_YPC_CAN_POST_OR_REACT_TO_COMMENT")?!0:!1};
var gI=function(a){var b=(0,m.I)(a,"id"),c=(0,m.C)("VIDEO_ID");(0,m.Wi)(a,"pending");(0,m.V)("/comment_servlet?field_approve_comment=1",{format:"XML",method:"POST",Z:{comment_id:b,entity_id:c,session_token:(0,m.Yk)("comment_servlet")},onError:function(){(0,m.gb)(a,"pending")}})};
var hI=function(a,b){var c={};c["action_"+(b?"":"un")+"block_commenter"]=1;var d=(0,m.I)(a,"id");(0,m.V)("/link_ajax",{format:"XML",method:"POST",ca:c,Z:{session_token:(0,m.Yk)("link_ajax"),comment_id:d},onSuccess:function(a,b){b&&b.success_message&&window.alert(b.success_message)},onError:function(a,b){b&&b.error_message&&window.alert(b.error_message)}})};
var jI=function(a,b){if(iI(!1)){var c=(0,m.I)(a,"id"),d=(0,m.C)("VIDEO_ID");m.P.hide(a);(0,m.gb)(a,"flagged");d={entity_id:d};d[b]=c;(0,m.V)("/comment_servlet",{format:"XML",method:"POST",ca:d,Z:{session_token:(0,m.Yk)("comment_servlet")},onError:function(){m.P.show(a);(0,m.Wi)(a,"flagged")}})}};
var kI=function(a){var b=(0,m.I)(a,"id"),c=(0,m.C)("VIDEO_ID");m.P.hide(a);(0,m.V)("/comment_servlet?remove_comment=1",{format:"XML",method:"POST",Z:{comment_id:b,entity_id:c,session_token:(0,m.Yk)("comment_servlet")},onError:function(){m.P.show(a)}})};
var lI=function(a){if(iI(!0))if((0,m.Bh)(a,"replying"))(0,m.Bh)(a,"replying")&&((0,m.Wi)(a,"replying"),a=(0,m.w)("comments-post-container",a),(0,m.A)(a));else{(0,m.gb)(a,"replying");var b=(0,m.w)("comments-post",(0,m.v)("watch-discussion")||(0,m.v)("watch-discussion")),b=(0,m.Bk)(b),c=window.document.createElement("div");c.className="comments-post-container";a.appendChild(c);c.appendChild(b);b=new TH(b);b.reset();c=(0,m.I)(a,"id");b.Va.reply_parent_id.value=c;if(a=(0,m.I)(a,"tag"))b.i=a;b.focus()}};
var mI=function(a,b){if(iI(!1)&&!(0,m.I)(a,"voted")){var c=(0,m.I)(a,"id"),d=(0,m.C)("VIDEO_ID"),e=(0,m.I)(a,"score")||"0",g=b?1:-1;(0,m.Ti)(a,"voted",g+"");b?(0,m.ml)(a,"voted-down","voted-up"):(0,m.ml)(a,"voted-up","voted-down");c={a:g,id:c,video_id:d,old_vote:e};(d=(0,m.I)(a,"tag"))&&(c.tag=d);(0,m.V)("/comment_voting",{format:"XML",method:"POST",ca:c,Z:{session_token:(0,m.Yk)("comment_voting")}})}};
var nI=function(a){var b=(0,m.I)(a,"id"),c=(0,m.C)("VIDEO_ID");(0,m.Wi)(a,"has-child");(0,m.gb)(a,"child");var d=(0,m.v)("parent-comment-loading");if(d){var e=(0,m.Bk)(d);(0,m.Hh)(e,a);m.P.show(e)}(0,m.V)("/comment_servlet?get_comment_parent=1",{format:"XML",method:"POST",Z:{comment_id:b,entity_id:c,session_token:(0,m.Yk)("comment_servlet")},onSuccess:function(b,c){var d=window.document.createElement("ul");d.innerHTML=c.html_content;d=(0,m.Nj)(d);(0,m.Hh)(d,a);(0,m.A)(e);(0,m.Fs)(d)},onError:function(b,
c){(0,m.gb)(a,"has-child");(0,m.Wi)(a,"child");(0,m.A)(e);c&&c.error_message?window.alert(c.error_message):window.alert("Request failed, please try later.")}})};var oI=function(){if(-2==pI){pI=(0,window.parseInt)((0,m.id)("ACTIVITY","-1"),10);(0,m.S)(window.document,"keypress",qI);(0,m.S)(window.document,"click",rI);var a=(0,m.C)("LIST_AUTO_PLAY_VALUE");a&&1<a||sI()}};var qI=function(){sI()};var rI=function(){sI()};var sI=function(){oI();var a=(0,m.J)();1E3>a-pI||(pI=a,(0,m.gd)("ACTIVITY",""+a))};
var tI=function(){return-1==pI||-2==pI?-1:Math.max((0,m.J)()-pI,0)};var uI=function(a){if(!a.metaKey&&!a.ctrlKey){var b=a.target;if("INPUT"!=b.tagName&&"TEXTAREA"!=b.tagName&&"SELECT"!=b.tagName&&"EMBED"!=b.tagName)switch(a.keyCode){case 78:a.shiftKey&&(0,m.H)("player-shortcut-next");break;case 80:a.shiftKey&&(0,m.H)("player-shortcut-prev");break;case 106:(0,m.H)("player-shortcut-rewind");break;case 108:(0,m.H)("player-shortcut-fast-forward");break;case 107:(0,m.H)("player-shortcut-play-pause")}}};
var vI=function(){(0,m.K)(window.document.body,"site-center-aligned")?(wI=!0,xI=(0,m.v)("watch-appbar-playlist"),PG=(0,m.w)("playlist-videos-list",xI),yI=(0,m.w)("toggle-autoplay",xI),zI=(0,m.w)("shuffle-playlist",xI),AI=(0,m.w)("toggle-menu-visibility",xI),BI=(0,m.w)("next-playlist-list-item",xI),CI=(0,m.w)("prev-playlist-list-item",xI),DI=(0,m.w)("playlist-info",xI),EI="currently-playing"):(wI=!1,xI=(0,m.v)("playlist"),PG=(0,m.v)("watch7-playlist-tray"),yI=(0,m.v)("watch7-playlist-bar-autoplay-button"),
zI=(0,m.v)("watch7-playlist-bar-shuffle-button"),AI=(0,m.v)("watch7-playlist-bar-toggle-button"),BI=(0,m.v)("watch7-playlist-bar-next-button"),CI=(0,m.v)("watch7-playlist-bar-prev-button"),DI=(0,m.v)("watch7-playlist-data"),FI=(0,m.v)("watch7-playlist-interstitial"),EI="playlist-bar-item-playing");if(xI&&PG){wI||(GI.push((0,m.S)((0,m.v)("watch7-playlist-scrollfloater-autoplay-toggle"),"click",HI)),II=m.P.Aj((0,m.v)("watch7-content")).y,JI.push((0,m.G)("page-scroll",KI)));var a=(0,m.C)("PLAYER_REFERENCE");
a&&a.addEventListener("onReady",LI);DI&&(MI="true"===(0,m.I)(DI,"initial-autoplay-state"));GI.push((0,m.S)(yI,"click",NI));GI.push((0,m.S)(zI,"click",OI));GI.push((0,m.S)(AI,"click",PI));GI.push((0,m.S)(BI,"click",function(a){QI(a,"bf_next")}));GI.push((0,m.S)(CI,"click",function(a){QI(a,"bf_prev")}));GI.push((0,m.tk)(PG,RI,"a"));GI.push((0,m.U)(PG,"click",SI,"yt-uix-button-playlist-remove-item"));JI.push((0,m.G)("navigate",TI));JI.push((0,m.G)("player-state-change",UI));JI.push((0,m.G)("player-error",
VI));JI.push((0,m.G)("player-shortcut-next",WI));JI.push((0,m.G)("player-shortcut-prev",XI));(0,m.C)("SKIP_TO_NEXT_VIDEO")&&YI(5);ZI();$I();aJ()}};var bJ=function(a,b){var c;if(b){if(!MI||cJ)return;var d=DI;d&&(c=(0,m.I)(d,"autoplay-clicktracking")||"")}d=BI;dJ(d.href,a||"bf_next",c,b);(0,m.od)(d.href)};var $I=function(){var a=OG();(0,m.y)(a,function(a){(0,m.Rs)(a)})};
var LI=function(a){var b=(0,m.C)("LIST_END_TIME");b||(b=a.getDuration());for(var c=5;0<c;c--)a.addCueRange("NEAR_END"+c,b-c,b-c+1);a.addEventListener("onCueRangeEnter",eJ)};var eJ=function(a){if("NEAR_END"==a.slice(0,-1)&&(a=(0,window.parseInt)(a.slice(-1),10),wI||(fJ(),gJ(a)),5==a&&(0,m.C)("PREFETCH_NEXT_PLAYLIST_VIDEO")&&MI&&!cJ)){a=DI;var b;a&&(b=(0,m.I)(a,"autoplay-clicktracking")||"");a=BI.href;dJ(a,"autoplay",b,!0);b=window.ytspf||{};window.spf&&b.enabled&&a&&window.spf.prefetch(a,{onPart:m.aA})}};
var aJ=function(){(0,m.H)("watch-list-change")};var YI=function(a,b){var c=b||"mr_meh";wI||fJ();hJ?iJ=(0,m.D)(function(){YI(a,c)},1E3):(gJ(a),0==a?bJ(c,!0):iJ=(0,m.D)(function(){YI(a-1,c)},1E3))};var jJ=function(){var a=DI;return!(!a||"False"==(0,m.I)(a,"shareable"))};var NI=function(){var a=(0,m.fo)(m.Qn.getInstance(),yI),b=m.Ud.getInstance();(0,m.th)(76,a);b.save();(0,m.yb)("LIST_AUTO_PLAY_ON",!a);MI=!a};
var HI=function(){var a=(0,m.C)("PLAYER_REFERENCE");a&&a.getPlayerState?1==a.getPlayerState()?a.pauseVideo():a.playVideo():((0,m.Nk)(xI,"paused"),hJ=!hJ)};var OI=function(){var a=PG,b=(0,m.Pa)(a.getElementsByTagName("li"));if((0,m.fo)(m.Qn.getInstance(),zI))b=kJ(b),(0,m.yb)("SHUFFLE_VALUE",0);else var c=lJ(b),b=mJ(b,c);(0,m.pb)(a);(0,m.y)(b,function(b){a.appendChild(b)});c=(0,m.C)("SHUFFLE_VALUE");nJ(b,c);ZI();$I();aJ()};
var PI=function(){if(wI){var a=(0,m.fo)(m.Qn.getInstance(),AI);(0,m.O)(xI,"watch-playlist-collapsed",a);a||ZI()}else(0,m.Nk)((0,m.v)("player"),"watch-playlist-collapsed")||(a=(0,m.KA)((0,m.v)("watch7-playlist-tray-container")),(0,m.D)($I,a))};var RI=function(a){var b=(0,m.Dh)(a.currentTarget,"li"),b=(0,m.I)(b,"clicktracking")||"";oJ(a,void 0,b)};var QI=function(a,b){var c=(0,m.I)(a.currentTarget,"clicktracking")||"";oJ(a,b,c)};
var oJ=function(a,b,c){var d=a.currentTarget.href;b=b||"BFa";var e={},g=(0,m.C)("SHUFFLE_VALUE");g?e.shuffle=g:-1!=d.indexOf("shuffle=")&&(e.shuffle=0);e&&(d=(0,m.Ek)(d,e));a.currentTarget.href=d;dJ(d,b,c)};
var SI=function(a){var b=DI,c=(0,m.Dh)(a.currentTarget,"li");if(b&&c){var d=PG;(0,m.L)(d,"playlist-editing-locked");a=(0,m.I)(b,"full-list-id");b=(0,m.I)(c,"video-id");(0,m.gu)({Da:b,Me:a,onSuccess:function(){(0,m.A)(c);var a=(0,m.ib)("li",null,d),b=1,h=0;(0,m.y)(a,function(a){if(!wI)if((0,m.K)(a,EI))h=b;else{var c=(0,m.ib)("span","count",a);c&&c[0]&&(c[0].innerHTML=b)}(0,m.Ti)(a,"index",b);b+=1});wI||((0,m.v)("watch7-playlist-current-index").innerHTML=h,(0,m.v)("watch7-playlist-length").innerHTML=
b-1);nJ(a,(0,m.C)("SHUFFLE_VALUE"))},qa:function(){(0,m.M)(d,"playlist-editing-locked");aJ()}})}};var pJ=function(a,b){var c={lact:a,event:"interstitialclick",delay:(0,m.J)()-b};(0,m.Nl)((0,m.jd)(c));m.P.hide(FI);(0,m.M)((0,m.v)("player"),"off-screen-trigger");qJ&&(0,m.F)(qJ);bJ("interstitial",!1)};var rJ=function(a,b){(0,m.Nl)((0,m.jd)({lact:a,event:"interstitialtimeout",delay:b}))};
var UI=function(a){if(0==a){var b;(0,m.C)("PLAYLIST_INTERSTITIAL")&&MI?(b=tI()/6E4,b=Math.min(0.005,8.34522E-4*Math.exp(0.100073*b)),b=Math.random()<b):b=!1;b?(m.P.show(FI),(0,m.L)((0,m.v)("player"),"off-screen-trigger"),(0,m.T)(sJ),b=tI(),sJ=(0,m.S)(FI,"click",(0,m.s)(pJ,b,(0,m.J)())),qJ=(0,m.D)((0,m.s)(rJ,b,18E4),18E4),(0,m.Nl)((0,m.jd)({lact:b,event:"interstitialshown"}))):(0,m.Jq)()||bJ("autoplay",!0)}tJ&&(2==a?(0,m.L)(xI,"paused"):1==a&&(0,m.M)(xI,"paused"))};var VI=function(){};var WI=function(){bJ("keys")};
var XI=function(){var a=CI;dJ(a.href,"keys");(0,m.od)(a.href)};var KI=function(a){tJ&&(a.y>II?(0,m.L)(xI,"scrolled"):a.y<II-50&&(0,m.M)(xI,"scrolled"))};var TI=function(){cJ=!0};
var mJ=function(a,b){function c(a){var c=0,d=[];for(a=a.split("");a.length;){var c=(b+c)%a.length,e=a[c];(0,m.Na)(a,c);d.push(e)}return d.join("")}(0,m.Uj)(a,function(a,b){var d=(0,m.I)(a,"video-id"),e=(0,m.I)(b,"video-id");return c(d).localeCompare(c(e))});var d=b>>8,e=(0,m.Ja)(a,function(a){a=(0,m.I)(a,"index");return d==a})||0;0<e&&(a=(0,m.Qa)(a,e).concat((0,m.Qa)(a,0,e)));return a};
var kJ=function(a){(0,m.Uj)(a,function(a,c){var d=(0,window.parseInt)((0,m.I)(a,"index"),10),e=(0,window.parseInt)((0,m.I)(c,"index"),10);return d-e});return a};var lJ=function(a){var b=(0,m.C)("SHUFFLE_VALUE");if(!b){var c=0;(0,m.y)(a,function(a){(0,m.K)(a,EI)&&(c=(0,m.I)(a,"index"))});b=(c<<8)+Math.floor(256*Math.random());(0,m.yb)("SHUFFLE_VALUE",b)}return b};
var nJ=function(a,b){var c=null;(0,m.y)(a,function(a){(0,m.K)(a,EI)&&(c=a)});if(c){var d=(0,m.dl)(c);d||(d=a[0]);var e=(0,m.cl)(c);e||(e=a[a.length-1]);var g=BI,h=CI;g&&d&&(d={v:(0,m.I)(d,"video-id")},b?d.shuffle=b:-1!=g.href.indexOf("shuffle=")&&(d.shuffle=0),g.href=(0,m.Ek)(g.href,d));h&&e&&(d={v:(0,m.I)(e,"video-id")},b?d.shuffle=b:-1!=h.href.indexOf("shuffle=")&&(d.shuffle=0),h.href=(0,m.Ek)(h.href,d))}};
var dJ=function(a,b,c,d){var e=(0,m.C)("EVENT_ID");e&&(e={ei:e},b&&(e.feature=b),c&&(e.ved=c),(b=(0,m.C)("SHUFFLE_VALUE"))&&(e.shuffle=b),MI||(e.autoplay_disabled=!0),(0,m.fo)(m.Qn.getInstance(),AI)?e.open_playlist=1:e.open_playlist=0,d&&(e.playnext=(0,m.C)("LIST_AUTO_PLAY_VALUE"),d=tI(),0<d&&(e.lact=d)),(0,m.md)(a,e))};var gJ=function(a){xI&&(0,m.Ti)(xI,"autoplay-countdown",a)};
var ZI=function(){var a=wI?(0,m.w)("playlist-videos-list"):PG,b=(0,m.w)(EI,a);if(b){var c=m.uq.getInstance();if(a&&b){var d=(0,m.R)((0,m.X)(c,"scroll-unit"),a),b=(0,m.La)(d,b);if(0<=b&&a&&!((0,window.isNaN)(b)||0>b)&&(c=(0,m.R)((0,m.X)(c,"scroll-unit"),a),!(0>=c.length))){b>=c.length&&(b=c.length-1);var d=NG(c),e=a.offsetHeight,g=Math.max(Math.floor(a.scrollTop/d),0);b>g-1&&(d=Math.floor(e/d),e=c.length,b+d>e&&(b=e-d+1));0>b&&(b=0);b=c[b].offsetTop;a&&!(0,window.isNaN)(b)&&(0>b&&(b=0),a.scrollTop=
b,(0,m.Ti)(a,"scroller-offset",b+""),m.gq.j(a))}}}};var fJ=function(){if(!0!=tJ&&MI){tJ=!0;(0,m.O)(xI,"playlist-floating",!0);var a=window.document,b=a.body,a=a.documentElement;KI(new m.Sa(b.scrollLeft||a.scrollLeft,b.scrollTop||a.scrollTop))}};
var uJ=function(){if(vJ)(0,m.yb)("PLAYER_REFERENCE",vJ);else{var a=(0,m.p)("ytplayer.config");if(a&&(a=(0,m.Tc)(a),vJ=(0,m.kf)("player-api")||(0,m.ef)("player-api",a),(0,m.yb)("PLAYER_REFERENCE",vJ),vJ)){var b=vJ;b.addEventListener("onReady",wJ);b.addEventListener("onStateChange",xJ);b.addEventListener("RATE_SENTIMENT",yJ);b.addEventListener("SHARE_CLICKED",zJ);b.addEventListener("SIZE_CLICKED",AJ);b.addEventListener("onError",BJ);b.addEventListener("WATCH_LATER_VIDEO_ADDED",CJ);b.addEventListener("WATCH_LATER_VIDEO_REMOVED",
DJ);b.addEventListener("onAdStart",EJ);(0,m.ME)(vJ,a.args.has_mdx_screens,!0);FJ();GJ=(0,m.Eb)(FJ,1E3);HJ.push((0,m.G)("player-shortcut-rewind",IJ));HJ.push((0,m.G)("player-shortcut-fast-forward",JJ));HJ.push((0,m.G)("player-shortcut-play-pause",KJ));HJ.push((0,m.G)("watch-list-change",LJ));HJ.push((0,m.G)("player-ad-start",MJ));(0,m.TE)(vJ);NJ.push((0,m.G)("sentiment-like",(0,m.s)(m.un,"like")),(0,m.G)("sentiment-dislike",(0,m.s)(m.un,"dislike")),(0,m.G)("sentiment-indifferent",(0,m.s)(m.un,"indifferent")));
OJ(NH)}}};var LJ=function(){var a=vJ;a&&a.isReady()&&a.updatePlaylist()};var MJ=function(){PJ=!0};var QJ=function(a,b){var c=RJ();if(c){var d=(0,m.id)(c,"").split(","),d=(0,m.Oc)(d,function(b){return 0!=b.indexOf(a)&&!!b.length});4<=d.length&&d.shift();d.push(a+":"+b);(0,m.gd)(c,d.join(","),1814400)}};var SJ=function(a){var b=RJ();if(b){var c=(0,m.id)(b,"").split(","),c=(0,m.Oc)(c,function(b){return 0!=b.indexOf(a)});0==c.length?(0,m.Hk)(b):(0,m.gd)(b,c.join(","),1814400)}};
var TJ=function(a){var b=(0,m.vs)();if(b){a&&(0,m.yb)("RESUME_COOKIE_NAME",a);a=(0,m.C)("VIDEO_ID");var c=b.getDuration(),b=Math.floor(b.getCurrentTime());0==c||120>=b||b+120>=c?SJ(a):QJ(a,Math.floor(b))}};var UJ=function(){var a=vJ;a&&a.sendAbandonmentPing&&a.sendAbandonmentPing();if(RJ()&&(TJ(),(0,m.C)("IS_RESUMABLE_PLAYBACK"))){var b=vJ;if(b){var a=(0,m.C)("VIDEO_ID"),c=b.getDuration(),b=Math.floor(b.getCurrentTime());0==c||20>=b||(0,m.wc)("/save_resume_204?"+(0,m.jd)({v:a,t:b.toString()}))}}};
var wJ=function(){var a=(0,m.C)("PLAYER_REFERENCE");if(a){(0,m.S)(window,"beforeunload",UJ);VJ(a.getPlayerState());var b=(0,m.C)("RELATED_PLAYER_ARGS");b&&a&&a.updateVideoData&&a.updateVideoData(b)}};var xJ=function(a){VJ(a);(0,m.H)("player-state-change",a)};var BJ=function(a){(0,m.H)("player-error",a)};var AJ=function(a){(0,m.gd)("wide",a?"1":"0");(0,m.H)("player-resize",a)};var yJ=function(a){(0,m.rh)(a)&&(a={videoId:(0,m.C)("VIDEO_ID"),sentiment:a});(0,m.H)("player-sentiment",a.videoId,a.sentiment)};
var zJ=function(){(0,m.H)("player-share")};var CJ=function(a){(0,m.H)("WATCH_LATER_VIDEO_ADDED",a)};var DJ=function(a){(0,m.H)("WATCH_LATER_VIDEO_REMOVED",a)};var EJ=function(a){(0,m.H)("player-ad-start",a)};var WJ=function(a,b){function c(){a.apply(this,arguments);d&&(0,m.Rb)(d);g&&(0,m.Rb)(g);(0,m.F)(e)}var d,e,g;if(d=XJ(c))g=OJ(c),b&&(e=(0,m.D)(c,b),YJ.push(e))};var XJ=function(a){var b=null;PJ?a():(b=(0,m.G)("player-ad-start",a),HJ.push(b));return b};
var OJ=function(a){var b=null;ZJ?a():(b=(0,m.G)("player-playback-start",a),HJ.push(b));return b};var KJ=function(){var a=vJ;a&&(2==a.getPlayerState()?a.playVideo():a.pauseVideo())};var JJ=function(){var a=vJ;if(a){var b=a.getCurrentTime();a.seekTo(b+10)}};var IJ=function(){var a=vJ;if(a){var b=a.getCurrentTime();a.seekTo(b-10)}};var $J=function(a,b){var c=vJ;if(c){var d=null!=b?b:!0;c.seekTo(a,!0);d&&window.scroll(0,0);2==c.getPlayerState()&&c.playVideo()}};
var FJ=function(){if(vJ&&vJ.isReady()){var a=window.location.hash;a!=aK&&(aK=a,a=(0,m.Ri)(a),"t"in a&&a.t!=bK.t&&$J((0,m.Ul)(a.t),!1),bK=a)}};var VJ=function(a){ZJ||1!=a&&2!=a&&0!=a||(ZJ=!0,(0,m.H)("player-playback-start"))};var RJ=function(){return(0,m.C)("RESUME_COOKIE_NAME")};var cK=function(a){dK=(0,m.uk)((0,m.v)("guide-loading-toggle"),"click",function(){(0,m.F)(eK.guide);fK(a,"click",!0)});eK.guide=(0,m.D)(function(){(0,m.T)(dK);fK(a,"time",!1)},3E3)};
var gK=function(a){var b=["related"];"playback"==a&&(WJ((0,m.s)(fK,b,"play")),a=1E4);(0,m.rh)(a)&&(eK.related=(0,m.D)(function(){fK(b,"time")},a))};
var hK=function(a){var b=(0,m.v)((0,m.C)("IS_ACTIVE_LIVE_VIDEO")&&!(0,m.C)("IS_DISTILLER")?"watch7-sidebar-discussion":"watch-discussion");if((0,m.Mj)(b)){(0,m.L)(b,"scrolldetect");(0,m.Ti)(b,"scrolldetect-callback","comments-delay-load");var c=(0,m.C)("WATCH_COMMENTS_LOAD_DELAY_PLAYBACK")?(0,m.J)()+1E4:(0,m.J)()+1E3;(0,m.fA)({"comments-delay-load":function(){(0,m.C)("WATCH_COMMENTS_LOAD_DELAY_PLAYBACK")&&WJ((0,m.s)(fK,a,"play"));var b=c-(0,m.J)();eK.comments=(0,m.D)((0,m.s)(fK,a,0<b?"time":"scroll"),
b)}})}};var fK=function(a,b,c){var d=(0,m.C)("VIDEO_ID");d||(0,m.Ma)(a,"comments");(0,m.Ka)(a,"comments")&&(0,m.EE)()&&(0,m.Ma)(a,"comments");if(a&&a.length){var e=(0,m.Fk)(window.location.href);e.v=d;e.tr=b;(0,m.Ka)(a,"comments")&&(0,m.C)("IS_DISTILLER")&&(e.distiller="1");(0,m.Jt)(a,c,e,(0,m.s)(iK,a))}};
var iK=function(a){if((0,m.Ka)(a,"comments")){if(!(0,m.EE)()){var b=(0,m.v)("comments-view");jK=new aI((0,m.v)("watch-discussion"));kK.push((0,m.U)(b,"click",fI,"comment-action"));if(b=(0,m.v)("comments-textarea"))b.disabled=!1,b.id="";(0,m.C)("COMMENT_OPEN_REPLY_BOX")&&(b=(0,m.R)("comment",(0,m.v)("linked-comments-header")),lI(b[b.length-1]));(0,m.Fs)((0,m.v)("comments-view"))}(b=(0,m.C)("JS_COMMENTS_MODULES"))&&(0,m.sc)(b)}(0,m.Ka)(a,"related")&&(vI(),(0,m.Fs)((0,m.v)("watch-related")),a=(0,m.C)("RELATED_PLAYER_ARGS"),
b=(0,m.C)("PLAYER_REFERENCE"),a&&b&&b.updateVideoData&&b.updateVideoData(a),(0,m.C)("SKIP_RELATED_ADS")||((0,m.C)("RELATED_ADS_DEFER")?WJ(hH,(0,m.C)("RELATED_ADS_DEFER_DEADLINE_MS",void 0)):oH()))};var lK=function(a,b,c){this.b=a;this.i=b;this.A=this.K=this.V=this.Q=this.S=this.N=this.R=this.X=this.$=this.k=this.D=this.B=this.g=this.j=this.L=this.C=null;this.K=(0,m.V)("/playlist_ajax",{ca:{action_get_addto_panel:1,video_id:this.i},onSuccess:function(a,b){mK(this,b.html);c()},O:this})};
var mK=function(a,b){a.b.innerHTML=b;a.L=(0,m.w)("sort-playlists",a.b);a.j=(0,m.w)("playlist-items",a.b);a.g=(0,m.w)("added-to-message",a.b);a.B=(0,m.w)("messages-area",a.b);a.D=(0,m.w)("create-playlist",a.b);a.D&&(a.k=(0,m.w)("new-playlist-title",a.b),a.$=(0,m.w)("create-new-playlist",a.b));a.X=(0,m.S)(a.L,"change",(0,m.r)(a.IB,a));a.R=(0,m.S)(a.D,"submit",(0,m.r)(a.MB,a));a.N=(0,m.U)(a.b,"click",(0,m.r)(a.KB,a),"playlist-item");a.S=(0,m.U)(a.b,"click",(0,m.r)(a.LB,a),"save-note");a.Q=(0,m.U)(a.b,
"click",(0,m.r)(a.JB,a),"cancel-note");a.V=(0,m.S)(a.k,"keyup",(0,m.r)(a.NB,a));nK(a,a.L.value);(0,m.Kp)()};var oK=function(a){(0,m.T)(a.X);(0,m.T)(a.R);(0,m.T)(a.N);(0,m.T)(a.S);(0,m.T)(a.Q);(0,m.T)(a.V)};var nK=function(a,b){var c={updated:(0,m.s)(a.sw,"time-updated"),created:(0,m.s)(a.sw,"time-created"),privacy:a.JI,"a-z":a.tw,"z-a":a.KI}[b];if(c){var d=(0,m.Pa)((0,m.R)("playlist-item",a.j));pK(a,d.sort((0,m.r)(c,a)))}};
var pK=function(a,b){var c=window.document.createDocumentFragment();(0,m.y)(b,function(a){c.appendChild(a)});(0,m.pb)(a.j);(0,m.Ih)(a.j,c)};var qK=function(a,b){(0,m.L)(b,"loading");m.P.hide(a.g);a.A=(0,m.qm)(b,{O:a,onSuccess:function(a,d){(0,m.M)(b,"loading");d.html?(oK(this),mK(this,d.html),d.show_feed_privacy_dialog&&(0,m.H)("SHOW-FEED-PRIVACY-ADD-TO-PLAYLIST-DIALOG",d.video_id,d.playlist_id)):d.errors&&this.vf(d.errors[0],!0)}})};
var rK=function(a,b){var c=(0,m.w)("playlist-video-count",a);c.innerHTML=(0,window.parseInt)(c.innerHTML,10)+b};var sK=function(a,b){(0,m.L)(b,"loading");(0,m.qm)(b,{Z:{session_token:(0,m.Yk)("playlist_video_ajax"),set_video_id:a.C},O:a,onSuccess:function(){tK(this);(0,m.M)(b,"loading")},onError:function(a,d){(0,m.M)(b,"loading");this.vf(d.errors[0],!0)}})};var tK=function(a){var b=(0,m.w)("selected",a.b);b&&((0,m.M)(b,"selected"),a.C=null)};
var uK=function(){(0,m.ta)("yt.net.apiloader.onApiLoaded_GOOGLE_JSAPI",function(){vK()})};var vK=function(){wK.GOOGLE_JSAPI=!0;(0,m.y)(xK.GOOGLE_JSAPI,function(a){a.call()});delete xK.GOOGLE_JSAPI};
var yK=function(a){this.j=a;this.i=[];this.B=this.pn=!1;this.A=this.b=this.k=this.g=null;var b=(0,m.r)(this.D,this),c=(0,m.C)("HL_LOCALE")||"en";if(a=zK.GOOGLE_JSAPI)wK.GOOGLE_JSAPI?b.call():(xK.GOOGLE_JSAPI||(xK.GOOGLE_JSAPI=[]),xK.GOOGLE_JSAPI.push(b),AK.GOOGLE_JSAPI||(uK(),b={callback:"yt.net.apiloader.onApiLoaded_GOOGLE_JSAPI"},c&&(b.language=c),a=(0,m.cd)(a,b),c=window.document.createElement("script"),c.src=a,window.document.body.appendChild(c),AK.GOOGLE_JSAPI=!0))};
var BK=function(a,b){var c=(0,m.v)("stats-optout-form");c&&(m.P.hide("stats-optout-success"),m.P.hide("stats-optout-error"),a.A=(0,m.qm)(c,{format:"XML",ca:{opt_out:b},onSuccess:function(){this.pn=b;m.P.show("stats-optout-success")},onError:function(){(0,m.v)("stats-opt-out-chbox").checked=!this.pn;m.P.show("stats-optout-error")}}))};var CK=function(a,b){var c=(0,m.I)(a,b);if(c){var d=(0,m.Q)(a,"watch-actions-stats-rats"),e=(0,m.I)(d,"current-"+b);e!=c&&((0,m.ml)(d,e,c),(0,m.Ti)(d,"current-"+b,c))}};
var DK=function(a,b,c){a=(0,m.w)("watch-actions-stats-rats",a.j);if(!a)return null;b=(0,m.I)(a,"current-"+b);return c&&b&&0==b.lastIndexOf(c,0)?b.substr(c.length):b};var EK=function(a){if(a.g&&a.B&&a.k){var b=DK(a,"metric-css","stats-metric-"),c=DK(a,"mode-css","stats-mode-");b&&c&&(a.b||(a.b=new window.google.visualization.LineChart(a.k)),FK(a,a.b,a.k,a.g.day||{},b in a.g?a.g[b][c]||{}:{}))}};
var FK=function(a,b,c,d,e){var g=new window.google.visualization.DataTable;g.addColumn("date","Date");g.addColumn("number","value");"cmp_data"in e?(g.addColumn("number","cmp_data"),d=fH(d.data||[],e.data||[],e.cmp_data||[])):d=fH(d.data||[],e.data||[]);(0,m.y)(d,function(a){a[0]=GK(a[0]);g.addRow(a)});e=e.opt||{};"hAxis"in e&&"viewWindow"in e.hAxis&&(d=e.hAxis.viewWindow,"min"in d&&!(d.min instanceof Date)&&(d.min=GK(d.min)),"max"in d&&!(d.max instanceof Date)&&(d.max=GK(d.max)));d=(0,m.bl)(c);(0,m.A)(c);
c.style.left="-5000px";(0,m.Ih)(a.j,c);try{b.draw(g,e)}catch(h){throw h;}finally{c.style.left="",(0,m.A)(c),d&&(0,m.Ih)(d,c)}};var GK=function(a){return new Date(a+6E4*(new Date(a)).getTimezoneOffset())};
var HK=function(a,b){this.B=a;this.D=b;this.g=(0,m.v)("watch-like-dislike-buttons");this.i="action-panel-details";var c=(0,m.I)(this.g,"vote-state"),c=(0,window.parseInt)(c,10);(0,window.isNaN)(c)&&(c=2);(0,m.Tk)(this.g,"vote-state");this.j=c;this.b=[];this.he=[];this.Nm=this.Rm=this.A=this.k=null;this.C=this.kr=0;IK(this);JK(this,this.i);c=(0,m.Ri)(window.location.hash).action;"share"==c?this.xr():"flag"==c?KK(this,"action-panel-report"):"stats"==c&&KK(this,"action-panel-stats");(0,m.C)("RECIPROCAL_CIRCLE_ADD_PROMO")&&
LK(this)};var MK=function(a){switch(a){case "action-panel-share":(0,m.zm)("share");(0,m.C)("CONVERSION_CONFIG_DICT")&&(0,m.rn)("share",(0,m.C)("CONVERSION_CONFIG_DICT").uid||"");break;case "action-panel-addto":(0,m.zm)("add_to_playlist")}};var NK=function(){var a=(0,m.w)("yt-uix-button-toggled",(0,m.v)("action-panel-share")),b;jJ()&&a?b=(0,m.I)(a,"video-id"):b=(0,m.C)("VIDEO_ID");return b};
var OK=function(){var a=null;if(jJ()){var b=(0,m.v)("share-with-playlist");if(!b||b&&b.checked)a=(a=DI)?(0,m.I)(a,"full-list-id"):""}return a};
var IK=function(a){a.he.push((0,m.G)("player-share",a.xr,a));a.he.push((0,m.G)("player-state-change",a.DG,a));a.he.push((0,m.G)("player-sentiment",a.zG,a));a.he.push((0,m.G)("livestreaming-likes-updated",a.CG,a));a.b.push((0,m.U)(a.B,"click",(0,m.r)(a.yG,a),"action-panel-trigger"));if((0,m.C)("LOGGED_IN")){var b=(0,m.v)("watch-dislike");a.b.push((0,m.S)((0,m.v)("watch-like"),"click",(0,m.r)(a.xG,a)));a.b.push((0,m.S)(b,"click",(0,m.r)(a.wG,a)))}(b=(0,m.v)("watch-share-button"))&&a.b.push((0,m.S)(b,
"click",(0,m.r)(a.AG,a)));var c=(0,m.v)("donation-box");if(c){var d=(0,m.w)("google-checkout-price",c);a.b.push((0,m.S)(d,"change",function(){(0,m.w)("google-checkout-donate",c).disabled=1>d.selectedIndex}));if(b=(0,m.v)("watch-donation-button")){var e=new m.cE;(0,m.qC)(e,b);(0,m.B)(a,e)}}a.he.push((0,m.G)("watch-video-liked",(0,m.r)(a.BG,a)))};
var PK=function(a,b,c){var d=0==a.j;QK(!1);(0,m.Bm)(b,c,{Sb:(0,m.C)("PLAYBACK_ID"),zv:(0,m.C)("STATION_ID"),onSuccess:(0,m.r)(function(a,g){var h;t:switch(c){case 1:h="sentiment-dislike";break t;case 0:h="sentiment-like";break t;default:h="sentiment-indifferent"}(0,m.H)(h,b);0==c?((0,m.H)("watch-video-liked"),(0,m.Mk)(this.g,"disliked","liked")):1==c?((0,m.H)("watch-video-disliked"),(0,m.Mk)(this.g,"liked","disliked")):(0,m.Pk)(this.g,["liked","disliked"]);h=(0,m.v)("watch-like");var k;if(k=0==c?
(0,m.I)(h,"unlike-tooltip"):(0,m.I)(h,"like-tooltip"))(0,m.Tk)(h,"tooltip-text"),h.title=k;this.j=c;0==c?((0,m.H)("yt-uix-videolike-liked"),"True"==g.show_feed_privacy_dialog&&(0,m.H)("SHOW-FEED-PRIVACY-LIKE-DIALOG",b)):d&&(0,m.H)("yt-uix-videolike-unliked")},a),onError:(0,m.r)(function(){RK(this,"action-panel-error")},a),qa:(0,m.r)(function(){QK(!0)},a)})};var QK=function(a){var b=(0,m.v)("watch-like-dislike-buttons");(0,m.D)(function(){(0,m.Ak)(b,a)},0)};
var SK=function(a,b){KK(a,"action-panel-share",b)};var KK=function(a,b,c){var d=(0,m.v)("watch7-secondary-actions");QG(m.Qn.getInstance(),d);if(d=(0,m.v)(b))d=TK(a,d),(0,m.L)(d,"yt-uix-button-toggled"),JK(a,b,c)};var UK=function(a){return(0,m.C)("ALLOW_RATINGS")?(0,m.C)("LOGGED_IN")?(0,m.C)("YPC_CAN_RATE_VIDEO")?!0:(RK(a,"action-panel-rental-required"),!1):(RK(a,"action-panel-login"),!1):(RK(a,"action-panel-ratings-disabled"),!1)};
var JK=function(a,b,c){if("action-panel-none"!=b){var d=(0,m.v)(b);if(d){var e=!!(0,m.I)(d,"auth-required"),d=!!(0,m.I)(d,"panel-loaded");if(e&&!(0,m.C)("LOGGED_IN"))RK(a,"action-panel-login");else if(d)RK(a,b);else switch(b){case "action-panel-details":b=(0,m.v)("action-panel-details");VK(a);(0,m.Ti)(b,"panel-loaded","true");RK(a,"action-panel-details");break;case "action-panel-share":WK(a,c);break;case "action-panel-addto":b=(0,m.v)("action-panel-addto");c=new lK(b,(0,m.C)("VIDEO_ID"),m.ea);(0,m.B)(a,
c);(0,m.Ti)(b,"panel-loaded","true");RK(a,"action-panel-addto");break;case "action-panel-transcript":XK(a);break;case "action-panel-stats":YK(a);break;case "action-panel-report":ZK(a)}}}};
var VK=function(a){var b=(0,m.w)("yt-uix-expander",(0,m.v)("action-panel-details"));b&&(a.b.push((0,m.S)((0,m.v)("watch-description-content"),"click",function(){if((0,m.K)(b,"yt-uix-expander-collapsed")){var a=m.Ep.getInstance(),d=a.Na(b);d&&((0,m.M)(d,(0,m.X)(a,"collapsed")),(0,m.K)(window.document.body,"visibility-logging-enabled")&&(0,m.ip)(d),a.i(d,"expander-action"))}})),(0,m.K)(b,"yt-uix-expander-collapsed")&&a.b.push((0,m.uk)(b,"click",function(){var a=(0,m.v)("watch-source-videos-list");a&&
(this.Rm=$G(a))})))};
var WK=function(a,b){var c=NK(),d=OK(),e=(0,m.v)("action-panel-share"),g=new m.QF((0,m.v)("watch-actions-share-panel"),c,d,function(){m.P.hide("watch-actions-share-loading")},!0,null,b,!1,(0,m.C)("SHARE_REFERER"),(0,m.C)("SHARE_CAPTION"));(0,m.B)(a,g);var h=(0,m.Eb)(function(){var a=(0,m.vs)(),b=m.P.qb(e);if(a&&b){var a=a.getCurrentTime(),b=Math.floor(a/3600),c=Math.floor(a%3600%60),a=(0<b?b+":":"")+(0,m.Gl)(Math.floor(a%3600/60),0<b?2:1)+":"+(0,m.Gl)(c,2);g.tj(a)}else(0,m.Fb)(h)},1E3);a.C=h;(0,m.Ti)(e,
"panel-loaded","true");RK(a,"action-panel-share")};var YK=function(a){var b=(0,m.v)("action-panel-stats");if(b){var c=new yK(b);(0,m.B)(a,c);a.A=aH((0,m.r)(function(a,e,g){g?(b.innerHTML=a,c.load(e)):RK(this,"action-panel-error")},a));(0,m.Ti)(b,"panel-loaded","true");RK(a,"action-panel-stats")}};
var ZK=function(a){var b,c=!1,d=!1,e=(0,m.v)("action-panel-report"),g=(0,m.r)(function(){RK(this,"action-panel-error")},a);(0,m.ge)((0,m.C)("REPORTVIDEO_CSS"));(0,m.pc)((0,m.C)("REPORTVIDEO_JS"),(0,m.r)(function(){this.la()||(c=!0,d&&c&&$K(e,b))},a));a.k=bH((0,m.r)(function(a,k){k?(d=!0,b=a,d&&c&&$K(e,b)):g()},a));(0,m.Ti)(e,"panel-loaded","true");RK(a,"action-panel-report")};var $K=function(a,b){a.innerHTML=b;(0,m.p)("yt.www.report.reportvideo.init")(!0)};
var XK=function(a){var b=(0,m.v)("action-panel-transcript");(0,m.p)("yt.www.watch.transcript.open")(function(){m.P.hide("watch-actions-transcript-loading");m.P.show((0,m.v)("watch-actions-transcript"))});(0,m.Ti)(b,"panel-loaded","true");RK(a,"action-panel-transcript")};
var RK=function(a,b){var c=aL[a.i],d=aL[b],e=(0,m.v)(a.i),g=(0,m.v)(b),h=a.D;if(d==c)(0,m.M)(h,"action-panel-transition"),(0,m.Pk)(e,["action-panel-center","action-panel-left","action-panel-right"]),m.P.show(e);else{a.i=b;m.P.show(e);h.style.height=h.clientHeight+"px";(0,m.L)(h,"action-panel-transition");if(d>c)var k="action-panel-right",n="action-panel-left";else k="action-panel-left",n="action-panel-right";(0,m.L)(e,"action-panel-center");(0,m.L)(g,k);m.P.show(g);(0,m.D)(function(){(0,m.M)(e,"action-panel-center");
(0,m.L)(e,n);(0,m.M)(g,k);(0,m.L)(g,"action-panel-center");this.kr=(0,m.D)(function(){m.P.hide(e);(0,m.M)(e,n);(0,m.M)(g,"action-panel-center");(0,m.M)(h,"action-panel-transition");h.style.height=""},(0,m.KA)(g))},0)}};var TK=function(a,b){var c=(0,m.R)("action-panel-trigger",a.B);return(0,m.Ia)(c,function(a){a=(0,m.I)(a,"trigger-for");return b.id==a})};
var LK=function(a){var b=(0,m.w)("yt-uix-clickcard-target",(0,m.v)("watch7-user-header")),c=(0,m.w)("rcap-dismiss-button",window.document);(0,m.Xr)("plus:follow",(0,m.Yr)(function(){var a=(0,m.w)("add-to-circle"),b=(0,m.p)("gapi.follow.render");b&&a&&(b(a,{href:(0,m.I)(a,"gplus-profile-url"),height:24,source:"youtube:topfans-follow-back"}),a.style.zIndex=2147483647)}));a.b.push((0,m.S)(c,"click",function(){this.Nm=(0,m.V)("/engagement_wizard_ajax",{method:"POST",ca:{action_dismiss_reciprocal_circle_add_promo:"1"},
Z:{session_token:(0,m.Yk)("engagement_wizard_ajax"),video_id:(0,m.C)("VIDEO_ID")}})}));m.no.getInstance().show(b)};var bL=function(){this.b=[];this.g=0;this.i=window.document.title;(0,m.vs)()&&this.cu(1);this.b.push((0,m.G)("page-resize",this.OD,this));this.b.push((0,m.G)("player-state-change",this.cu,this));this.b.push((0,m.G)("player-resize",this.PD,this));this.dl()};var cL=function(a){1==a&&(0,m.Pz)()};
var dL=function(a,b){if(!eL&&b.swfcfg){var c=b.swfcfg.args,d=vJ;d&&d.preloadVideoByPlayerVars&&c&&d.preloadVideoByPlayerVars(c);eL=!0}};var fL=function(a){(0,m.Dh)(a.target,"BUTTON")||a.currentTarget.click()};m.KF.prototype.tj=(0,m.sh)(25,function(){if(this.Nx&&this.media){var a=(0,m.vs)(),b=Math.round(1E3*a.getCurrentTime()),b=[b,b+1E3],b=(0,m.LF)(this,b,!0);(0,m.OF)(this,b,1!=a.getPlayerState())}});
m.QF.prototype.tj=(0,m.sh)(24,function(a){!this.g||(0,m.Bh)(this.g,"focused")||this.ha||(this.g.value=a,this.hi(),m.P.qb(this.k)&&this.N&&this.N.tj())});var gL=[],NJ=[],jK,eI,kH,iH,hL,iL;m.f=gH.prototype;m.f.jg=!1;m.f.aj=!1;m.f.start=function(a){var b={start:0};b.end=a.scrollHeight-a.clientHeight;b.duration=b.end/3;b.Oi="linear";this.b=new m.gB(a,b);this.jg=!0;this.g.listen(a,"click",this.uF);this.g.listen(a,"mouseover",this.wF);this.g.listen(a,"mouseout",this.tF);this.g.listen(a,"scroll",this.vF)};
m.f.vF=function(){this.aj||this.jg||(this.b.pause(),this.aj=!0)};m.f.uF=function(){this.b.pause();this.jg=!1;this.aj=!0};m.f.wF=function(){this.b.pause();this.jg=!1};m.f.tF=function(){this.jg||this.aj||(this.b.play(),this.jg=!0)};m.f.dispose=function(){this.g.removeAll();this.aj=this.jg=!1;this.b=null;this.i=!0};m.f.la=function(){return this.i};var GH="",HH="",JH=!1,xH=!1,zH=null,lH=null,KH=0,pH=null,qH=null,rH=null,yH=!1;(0,m.l)("yt.www.watch.ads.setAdId",function(a){window.ad_debug=a},void 0);(0,m.l)("yt.www.watch.ads.setCompanion",AH,void 0);(0,m.l)("yt.www.watch.ads.showForcedMpu",function(a){var b=BH(a);a=CH(a);AH(b,a)},void 0);(0,m.l)("yt.www.watch.ads.setGutSlotSizes",function(a,b){if(pH){var c=pH.getSizes();(0,m.Cl)(c);b&&c.push(qH);a&&c.push(rH)}},void 0);
(0,m.l)("yt.www.watch.ads.handleSetCompanion",function(a){a=a.replace(";dc_seed=",";kmyd=watch-channel-brand-div;dc_seed=");var b=BH(a);a=CH(a);AH(b,a)},void 0);(0,m.l)("yt.www.watch.ads.handleSetCompanionForFreewheel",DH,void 0);(0,m.l)("yt.www.watch.ads.handleSetAfvCompanionVars",EH,void 0);(0,m.l)("yt.www.watch.ads.companionSetupComplete",FH,void 0);(0,m.l)("yt.www.watch.ads.pauseVideo",IH,void 0);(0,m.l)("yt.www.watch.ads.loadAfc",tH,void 0);
(0,m.l)("yt.www.watch.ads.isAfcAdVisible",function(){var a=(0,m.v)("google_companion_ad_div");return a?(a=(0,m.Nj)(a))&&"IFRAME"==a.tagName?(0,m.Da)(a.src,"youtube.com/ad_frame"):!1:!1},void 0);(0,m.l)("yt.www.watch.ads.checkInit",uH,void 0);
(0,m.l)("yt.www.watch.ads.initVideoWallCompanionListeners",function(a,b){GH=a;HH=b;window.addEventListener("message",function(a){"companion-setup-complete"==a.data?FH():"pause-video"==a.data?IH():"resize-companion"==a.data&&(a=window.document.getElementById("google_companion_ad_div"))&&(a=a.firstElementChild)&&(a.height=210)},!1)},void 0);(0,m.l)("yt.www.ads.pyv.pyvWatchAfcWithPpvCallback",function(a){YG(a);0<a.length&&XG()},void 0);(0,m.l)("yt.www.ads.pyv.pyvWatchAfcCallback",YG,void 0);
(0,m.l)("yt.www.ads.pyv.pyvHomeAfcCallback",m.dD,void 0);(0,m.l)("yt.www.ads.pyv.showPpvOnWatch",UG,void 0);(0,m.l)("yt.www.ads.pyv.loadPyvIframe",WG,void 0);(0,m.l)("yt.www.watch.ads.restrictioncookie.spr",m.VC,void 0);(0,m.l)("setFreewheelCompanion",DH,void 0);(0,m.l)("setAfvCompanionVars",EH,void 0);var MH=null,OH=!1;m.f=TH.prototype;m.f.destroy=function(){(0,m.T)(this.k);this.k=[];(0,m.y)(this.j,function(a){(0,m.Fb)(a)});this.j=[];(0,m.Tk)(this.Va,"initialized")};m.f.reset=function(){WH(this);YH(this);(0,m.Wi)(this.Va,"has-focus");this.hf.disabled=!1;this.Lc.value="";UH(this);this.Lc.blur();this.i=null;this.destroy();(0,m.H)("comment-form-reset")};m.f.focus=function(){this.Lc.focus()};m.f.ks=function(){this.Lc.readOnly||UH(this)};m.f.HA=function(a){if(this.B)switch(a.keyCode){case 13:this.is(a);break;case 27:this.reset()}};
m.f.ls=function(){(0,m.Bh)(this.Va,"has-focus")||m.P.hide(this.Pf);(0,m.gb)(this.Va,"has-focus");(0,m.H)("comments-focus",this.Va)};m.f.GA=function(){(0,m.H)("comments-blur",this.Va)};
m.f.is=function(a){a.preventDefault();if(!this.hf.disabled){this.hf.disabled=!0;this.Lc.readOnly=!0;a=(0,m.ti)((0,m.im)(this.Va));a.screen=(0,m.jd)({h:window.screen.height,w:window.screen.width,d:window.screen.colorDepth});var b=a.comment,b={return_ajax:"true",len:b.length,wc:b.split(/\s+/).length};this.Va.reply_parent_id.value&&(b.reply=1);this.i&&(b.tag=this.i);var c=(0,m.C)("PLAYBACK_ID");c&&(a.plid=c);(0,m.V)(this.Va.action,{format:"XML",method:"POST",ca:b,Z:a,qa:function(a,b){var c=b.str_code;
switch(c){case "OK":c=window.document.createElement("ul");c.innerHTML=b.html_content;c=(0,m.Nj)(c);if(this.Va.reply_parent_id.value){var h=(0,m.Dh)(this.Va,null,"comments-post-container"),k=(0,m.Dh)(h,null,"comment");(0,m.A)(h);(0,m.ml)(k,"replying","has-child");(0,m.gb)(c,"child");(0,m.Oj)(c,"last",!(0,m.dl)(k));(0,m.il)(c,k)}else this.oA?this.Ur.appendChild(c):(0,m.hl)(this.Ur,c,0),this.reset();(0,m.Rs)(c);(0,m.H)("comment-submit-success");"True"==b.show_feed_privacy_dialog&&(0,m.H)("SHOW-FEED-PRIVACY-COMMENT-DIALOG",
(0,m.C)("VIDEO_ID"),b.time_created);break;case "PENDING":WH(this);this.Tr.innerHTML=(0,m.Kb)("COMMENT_PENDING");(0,m.ml)(this.Pf,"yt-alert-error","yt-alert-info");m.P.show(this.Pf);break;default:$H(this,c,b)}this.Lc.readOnly=!1},O:this});(0,m.C)("CONVERSION_CONFIG_DICT")&&(0,m.rn)("comment",(0,m.C)("CONVERSION_CONFIG_DICT").uid||"");(0,m.zm)("comment")}};aI.prototype.destroy=function(){(0,m.T)(this.b);this.b=[]};aI.prototype.j=function(a){a.preventDefault();(0,m.Bh)(a.currentTarget,"yt-uix-button-toggled")||(m.P.hide(this.gt),(0,m.H)("comments-page-changing"),this.xj?this.g(2):bI(this,(0,m.r)(this.g,this,2)))};
aI.prototype.g=function(a){var b=(0,m.v)("comments-view");b.appendChild(this.xj);(0,m.Rs)(b);if(b=(0,m.v)("comments-textarea"))b.disabled=!1,b.id="";if(b=(0,m.w)("comment-list",this.ia)){var c=(0,m.w)("live-comments-setting",this.ia);(0,m.H)("comments-page-changed",b,c,a)}else(0,m.H)("comments-page-changed");bI(this)};var kK=[];var pI=-2;var wI=!1,GI=[],JI=[],tJ=!1,hJ=!1,cJ=!1,II=null,xI=null,PG=null,yI=null,zI=null,AI=null,BI=null,CI=null,DI=null,FI=null,sJ=null,qJ=null,EI="",iJ=null,MI=!1;var vJ,HJ=[],PJ=!1,ZJ=!1,aK="",bK={},GJ=0,YJ=[];var dK,eK={};(0,m.u)(lK,m.ub);m.f=lK.prototype;m.f.H=function(){this.K&&this.K.abort();this.A&&this.A.abort();oK(this);lK.F.H.call(this)};m.f.IB=function(a){a=a.currentTarget.value;nK(this,a);(0,m.V)("/playlist_ajax?action_update_addto_sort_criteria=1",{ca:{criteria:a}})};m.f.JI=function(a,b){var c=(0,m.I)(a,"is-private")||"",d=(0,m.I)(b,"is-private")||"";return(0,m.dj)(c,d)};
m.f.sw=function(a,b,c){b=(0,window.parseInt)((0,m.I)(b,a),10)||window.Infinity;return((0,window.parseInt)((0,m.I)(c,a),10)||window.Infinity)-b};m.f.tw=function(a,b){var c=(0,m.I)(a,"title")||"",d=(0,m.I)(b,"title")||"";return(0,m.dj)(c,d)};m.f.KI=function(a,b){return this.tw(b,a)};m.f.MB=function(a){a.preventDefault();a=(0,m.w)("create-playlist",this.b);(0,m.ej)(this.k.value)||qK(this,a)};
m.f.KB=function(a){if(!(0,m.Q)(a.target,"playlist-note-form"))if(a.stopPropagation(),tK(this),m.P.hide(this.g),a=a.currentTarget,(0,m.K)(a,"contains-all-selected-videos")){var b=(0,m.I)(a,"full-list-id");(0,m.L)(a,"loading");(0,m.gu)({Da:this.i,Me:b,onSuccess:(0,m.s)(this.QG,a),onError:(0,m.s)(this.qv,a),O:this})}else b=(0,m.I)(a,"full-list-id"),(0,m.L)(a,"loading"),(0,m.fu)({Da:this.i,Me:b,onSuccess:(0,m.s)(this.PG,a),onError:(0,m.s)(this.qv,a),O:this})};
m.f.QG=function(a,b,c){(0,m.Pk)(a,["loading","contains-all-selected-videos"]);rK(a,-1);c.html_content&&this.vf(c.html_content,!1);(0,m.H)("PLAYLIST_UPDATED")};
m.f.PG=function(a,b,c){b=c.result;this.C=b.set_video_ids[0];(0,m.Mk)(a,"loading","contains-all-selected-videos");rK(a,1);b.message&&this.vf(b.message,!1);"True"==b.show_private_video_warning&&(c=(0,m.w)("private-video-warning",(0,m.w)("watch-playlist-drawer")))&&m.P.show(c);c=(0,m.I)(a,"list-type");var d="favorites"==c;d||"watch-later"==c||(0,m.L)(a,"selected");d?(a="playlist-favorite",c="SHOW-FEED-PRIVACY-FAVORITE-DIALOG"):(a="playlist-addto",c="SHOW-FEED-PRIVACY-ADD-TO-PLAYLIST-DIALOG");(0,m.H)(a,
this.i,b.full_list_id);"True"==b.show_feed_privacy_dialog&&(0,m.H)(c,this.i,b.full_list_id);(0,m.H)("PLAYLIST_UPDATED")};m.f.qv=function(a,b,c){(0,m.M)(a,"loading");this.vf(c.errors[0],!0)};m.f.LB=function(a){a.preventDefault();m.P.hide(this.g);a=(0,m.Q)(a.currentTarget,"playlist-note-form");sK(this,a)};m.f.JB=function(){tK(this)};m.f.vf=function(a,b){b?(0,m.ss)(a,this.g,this.B):(0,m.ts)("yt-alert-success",a,this.g,this.B)};m.f.NB=function(){this.$.disabled=(0,m.ej)(this.k.value)};var zK={GOOGLE_MAPS_API:"//maps.google.com/maps/api/js?sensor=false",GOOGLE_LANGUAGE_API_VIRTUAL_KEYBOARD:"//www.google.com/jsapi?key=youtube-internal-vk",GOOGLE_LANGUAGE_API_INPUT_TOOLS:"//www.google.com/jsapi?key=youtube-internal-it",GOOGLE_PLUS_ONE:"//apis.google.com/js/platform.js",GOOGLE_JSAPI:"//www.google.com/jsapi"},AK={},wK={},xK={};(0,m.u)(yK,m.ub);yK.prototype.H=function(){(0,m.T)(this.i);this.i.length=0;this.A&&this.A.abort();this.b&&(this.b.clearChart(),this.b=null);yK.F.H.call(this)};
yK.prototype.load=function(a){var b=(0,m.v)("stats-opt-out-chbox");b&&(this.pn=!b.checked,this.i.push((0,m.S)(b,"change",(0,m.r)(function(){BK(this,!b.checked)},this))));this.i.push((0,m.U)(this.j,"click",(0,m.r)(function(a){CK(a.currentTarget,"mode-css");EK(this)},this),"stats-mode-button"));this.i.push((0,m.U)(this.j,"click",(0,m.r)(function(a){CK(a.currentTarget,"top-site-css");CK(a.currentTarget,"metric-css");EK(this)},this),"stats-bragbar"));(0,m.In)(m.dr);a&&(this.g=(0,m.Yj)(a));this.k=(0,m.w)("stats-chart-gviz",
this.j);EK(this)};yK.prototype.D=function(){window.google.load("visualization","1.0",{packages:["corechart"],callback:(0,m.r)(this.C,this),language:(0,m.C)("HL_LOCALE")||"en"})};yK.prototype.C=function(){this.B=!0;EK(this)};(0,m.u)(HK,m.ub);var aL={"action-panel-details":1,"action-panel-share":2,"action-panel-addto":3,"action-panel-transcript":4,"action-panel-stats":5,"action-panel-report":6,"action-panel-login":7,"action-panel-ratings-disabled":8,"action-panel-rental-required":9,"action-panel-error":10};m.f=HK.prototype;
m.f.H=function(){(0,m.T)(this.b);this.b.length=0;(0,m.Rb)(this.he);this.he.length=0;(0,m.F)(this.kr);(0,m.Fb)(this.C);this.k&&this.k.abort();this.A&&this.A.abort();this.Rm&&this.Rm.abort();this.Nm&&this.Nm.abort();HK.F.H.call(this)};m.f.xG=function(){var a=0==this.j?2:0;UK(this)&&PK(this,(0,m.C)("VIDEO_ID"),a)};m.f.wG=function(){var a=1==this.j?2:1;UK(this)&&PK(this,(0,m.C)("VIDEO_ID"),a)};m.f.BG=function(){KK(this,"action-panel-share")};m.f.xr=function(){SK(this);MK("action-panel-share")};
m.f.DG=function(a){0==a?(0,m.C)("SHARE_ON_VIDEO_END")&&SK(this,!0):1==a&&(0,m.C)("SHARE_ON_VIDEO_START")&&SK(this,!0)};m.f.AG=function(){var a=(0,m.v)("watch7-secondary-actions");QG(m.Qn.getInstance(),a)};m.f.zG=function(a,b){UK(this)&&PK(this,a,b)};m.f.yG=function(a){a=(0,m.I)(a.currentTarget,"trigger-for");var b=(0,m.v)("watch-share-button");b&&(0,m.K)(b,"yt-uix-button-toggled")&&(0,m.M)(b,"yt-uix-button-toggled");JK(this,a);MK(a)};
m.f.CG=function(a,b,c,d){var e=(0,m.v)("watch7-views-info"),g=(0,m.w)("likes-count",e);g&&(0,m.al)(g,a);(a=(0,m.w)("dislikes-count",e))&&(0,m.al)(a,b);if(b=(0,m.w)("video-extras-sparkbar-likes",e))b.style.width=c+"%";if(c=(0,m.w)("video-extras-sparkbar-dislikes",e))c.style.width=d+"%"};m.f=bL.prototype;m.f.dispose=function(){(0,m.F)(this.g);(0,m.Rb)(this.b);this.b.length=0};m.f.OD=function(){this.dl()};m.f.cu=function(a){m.Wg||(window.document.title=1==a?"\u25b6 "+this.i:this.i)};
m.f.PD=function(a){a=!!a;var b=(0,m.v)("watch7-container"),c=(0,m.v)("player"),d=(0,m.v)("watch7-sidebar");if(b&&c&&d){var e=(0,m.KA)(d);if(a)(0,m.L)(b,"watch-wide"),(0,m.M)(b,"watch-non-stage-mode"),(0,m.L)(c,"watch-playlist-collapsed"),(0,m.M)(c,"watch-non-stage-mode"),(0,m.F)(this.g),this.g=(0,m.D)((0,m.r)(this.dl,this),e);else if((0,m.M)(b,"watch-wide"),(0,m.L)(b,"watch-non-stage-mode"),(0,m.M)(c,"watch-playlist-collapsed"),(0,m.L)(c,"watch-non-stage-mode"),this.dl(),(0,m.Rs)(d),b=(0,m.v)("watch7-playlist-tray-container"))b=
(0,m.KA)(b),(0,m.D)($I,b);if(b=(0,m.v)("watch-appbar-playlist"))c=(0,m.fo)(m.Qn.getInstance(),(0,m.w)("toggle-menu-visibility",b)),(0,m.O)(b,"watch-playlist-collapsed",a&&!c)}};
m.f.dl=function(){(0,m.F)(this.g);var a=(0,m.v)("player"),b=(0,m.v)("watch7-container");if(b&&a){var c=(0,m.K)(b,"watch-wide"),b=(0,m.Zo)();if(c){var c=!!(0,m.C)("ENABLE_AUTO_LARGE"),d=(0,m.K)(window.document.body,"site-center-aligned")&&((0,m.K)(window.document.body,"watch-early-bigbear")||(0,m.K)(window.document.body,"appbar-flexwatch")||(0,m.K)(window.document.body,"appbar-flexwatch-mini")),e=(0,m.K)(window.document.body,"appbar-flexwatch-540")||(0,m.K)(window.document.body,"appbar-flexwatch-540-mini"),
g=1E3<=b.width&&750<=b.height,b=b.width>=(d?1320:1540)&&b.height>=(d?930:1040);c&&b?((0,m.Pk)(a,["watch-medium","watch-medium-540","watch-small"]),(0,m.L)(a,"watch-large")):e&&g?((0,m.Pk)(a,["watch-small","watch-medium","watch-large"]),(0,m.L)(a,"watch-medium-540")):((0,m.Pk)(a,["watch-small","watch-medium-540","watch-large"]),(0,m.L)(a,"watch-medium"))}else(0,m.Pk)(a,["watch-medium","watch-medium-540","watch-large"]),(0,m.L)(a,"watch-small")}};var eL,jL=[];var kL=[],lL=[];(0,m.l)("yt.www.watch.player.init",uJ,void 0);
(0,m.l)("yt.www.watch.player.dispose",function(){(0,m.Fb)(GJ);(0,m.sk)(window,"beforeunload",UJ);(0,m.Rb)(NJ);NJ=[];(0,m.SE)();(0,m.cF)();if(vJ){var a=vJ;a.removeEventListener("onReady",wJ);a.removeEventListener("onStateChange",xJ);a.removeEventListener("RATE_SENTIMENT",yJ);a.removeEventListener("SHARE_CLICKED",zJ);a.removeEventListener("SIZE_CLICKED",AJ);a.removeEventListener("onError",BJ);a.removeEventListener("WATCH_LATER_VIDEO_ADDED",CJ);a.removeEventListener("WATCH_LATER_VIDEO_REMOVED",DJ);a.removeEventListener("onAdStart",
EJ)}vJ=null;ZJ=PJ=!1;aK="";bK={};(0,m.Rb)(HJ);HJ.length=0;for(a=YJ.length;a--;)(0,m.F)(YJ[a])},void 0);(0,m.l)("yt.www.watch.player.seekTo",$J,void 0);(0,m.l)("yt.www.watch.player.play",function(){var a=vJ;a&&a.playVideo()},void 0);(0,m.l)("yt.www.watch.player.pause",function(){var a=vJ;a&&a.pauseVideo()},void 0);(0,m.l)("yt.www.watch.player.saveResumeOffset",TJ,void 0);
(0,m.l)("yt.www.watch.player.handleEndPreview",function(a){var b=vJ;b&&b.stopVideo&&b.stopVideo();(b=(0,m.v)("watch-checkout-offers"))&&(0,m.H)("ypc-init-purchase-for-container",b,a)},void 0);(0,m.l)("yt.tracking.social.onAdvertiserVideoView",m.qn,void 0);(0,m.l)("checkCurrentVideo",function(a,b,c){var d=(0,m.C)("VIDEO_ID");d&&d!=a&&(a=c?c:(0,m.Ek)(window.location.href,{v:a,list:b}))&&(0,m.nd)(a)},void 0);
(0,m.l)("yt.www.watch.related.loadMore",function(){m.P.hide("watch-more-related-button");m.P.show("watch-more-related");ZG(function(){(0,m.Rs)((0,m.v)("watch-more-related"))})},void 0);(0,m.l)("yt.www.comments.initForm",dI,void 0);(0,m.l)("yt.www.thumbnaildelayload.classifyAndLoadVisibleImages",m.Fs,void 0);(0,m.l)("yt.www.watch.lists.loadThumbnails",$I,void 0);
(0,m.l)("yt.www.watch.lists.getState",function(){var a=[],b={},c=-1,d=[],e=PG;if(!e)return null;(0,m.y)(e.getElementsByTagName("li"),function(e,h){(0,m.K)(e,EI)&&(c=h);var k=(0,m.I)(e,"video-id"),n=(0,m.I)(e,"video-username"),t=(0,m.I)(e,"video-title"),n={id:k,username:n,title:t},t=(0,m.I)(e,"video-clip-start"),z=(0,m.I)(e,"video-clip-end");a[h]=k;b[k]=n;d[h]={start:t,end:z}});e=DI;return{author:(0,m.I)(e,"list-author"),autoPlay:MI,clipRanges:d,index:c,list:(0,m.I)(e,"full-list-id"),listTitle:(0,m.I)(e,
"list-title"),listDescription:(0,m.I)(e,"list-description"),videoData:b,videoIds:a}},void 0);(0,m.l)("yt.www.watch.activity.getTimeSinceActive",tI,void 0);(0,m.l)("yt.www.watch.activity.setTimestamp",sI,void 0);(0,m.l)("yt.sharing.facebooktokenrefresh.finish",function(a){var b={session_token:(0,m.Yk)("social_connector_ajax"),service:"facebook"},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);(0,m.V)("/social_connector_ajax",{method:"POST",format:"JSON",ca:{action_connect_service:1},Z:b})},void 0);
(0,m.l)("yt.abuse.invokeBotguard",function(){return MH?MH.invoke():null},void 0);(0,m.l)("yt.abuse.botguardInitialized",function(){return null!=MH},void 0);
(0,m.Ub)((0,m.Vk)({name:"www/watch",deps:["www/common"],page:"watch",init:function(){uJ();var a=(0,m.v)("watch7-action-buttons"),b=(0,m.v)("watch7-action-panels");iL=null;a&&b&&(iL=new HK(a,b));hL=new bL;oI();(0,m.S)(window.document,"keypress",uI);(0,m.C)("SKIP_RELATED_ADS")||((0,m.C)("RELATED_ADS_DEFER")?WJ(hH,(0,m.C)("RELATED_ADS_DEFER_DEADLINE_MS",void 0)):hH());vI();if((0,m.C)("BRANDED_BACKGROUND_IMAGE")||(0,m.C)("BRANDED_BACKGROUND_COLOR")){(0,m.L)((0,m.v)("guide-container"),"branded");var a=
(0,m.v)("player"),b=(0,m.C)("BRANDED_BACKGROUND_IMAGE"),c=(0,m.C)("BRANDED_BACKGROUND_COLOR");b&&(a.style.background="transparent url("+b+") no-repeat center top",(0,m.K)(window.document.body,"site-left-aligned")&&(a.style.backgroundPosition="left top"));c&&(a.style.backgroundColor=c)}a=(0,m.v)("watch7-sidebar");gL.push((0,m.U)(a,"click",TG,"related-action"));gL.push((0,m.U)(a,"click",SG,"resumable-list"));jL.push((0,m.G)("prefetch",dL));(a=(0,m.C)("PLAYER_REFERENCE"))&&a.getPlayerState&&1==a.getPlayerState()?
(0,m.Pz)():jL.push((0,m.G)("player-state-change",cL));m.xd&&(!window.document.documentMode||8>window.document.documentMode)&&kL.push((0,m.U)(window.document.body,"click",fL,"video-thumb"));(0,m.Et)(1);a=(0,m.C)("RELATED_DELAY_LENGTH");b=!!(0,m.w)("guide-module-loading");c=3E3==a;if(b){var d=["guide"];c&&d.push("related");cK(d)}!a||b&&c||gK(a);a=[];(0,m.C)("WATCH_COMMENTS_FORCE_DISABLED")||a.push("comments");(0,m.C)("DELAY_LOAD_FOOTER")&&a.push("footer");hK(a);(0,m.CB)();(0,m.C)("FACEBOOK_TOKEN_REFRESH_ENABLED")&&
(a=(0,m.v)("facebook_token_refresh_iframe"),b=(0,m.C)("FACEBOOK_TOKEN_REFRESH_URL"),a&&(0,m.Oe)("facebook_token_refresh")!=b&&((0,m.Le)("facebook_token_refresh",b,3600),a.src=b))},dispose:function(){iL&&((0,m.wb)(iL),iL=null);hL&&((0,m.wb)(hL),hL=null);(0,m.sk)(window.document,"keypress",qI);(0,m.sk)(window.document,"click",rI);pI=-2;(0,m.sk)(window.document,"keypress",uI);null!=window.adModuleLoaded&&(0,m.Xk)("adModuleLoaded");(0,m.F)(KH);lH&&(lH=null);iH&&(iH.dispose(),iH=null);kH=rH=qH=pH=null;
yH=JH=!1;if(zH){for(var a=zH.length-1;0<=a;a--)(0,m.Xk)(zH[a]);zH=[]}(0,m.YC)();gJ(0);(0,m.T)(GI);GI.length=0;if((a=(0,m.C)("PLAYER_REFERENCE"))&&a.getApiInterface){a.removeEventListener("onCueRangeEnter",eJ);a.removeEventListener("onReady",LI);for(var b=5;0<b;b--)a.removeCueRange("NEAR_END"+b)}(0,m.Rb)(JI);JI.length=0;xI&&(0,m.M)(xI,"scrolled");II=null;cJ=hJ=tJ=!1;DI=CI=BI=AI=zI=PG=yI=xI=null;EI="";wI=!1;iJ&&((0,m.F)(iJ),iJ=null);(a=(0,m.v)("guide-container"))&&(0,m.M)(a,"branded");if(a=(0,m.v)("player"))a.style.background=
"";gL&&((0,m.T)(gL),gL=[]);eL=!1;(0,m.Rb)(jL);jL.length=0;(0,m.T)(kL);kL.length=0;(0,m.Rb)(lL);lL.length=0;for(var c in eK)(0,m.F)(eK[c]);eK={};(0,m.T)(dK);eI&&(eI.destroy(),eI=null);jK&&(jK.destroy(),jK=null);(0,m.FE)();(0,m.T)(kK);kK.length=0}}));})(_yt_www);
